fix

diff --git a/scripts/manjaro-browsers-pipemenu b/scripts/manjaro-browsers-pipemenu
--- a/scripts/manjaro-browsers-pipemenu
+++ b/scripts/manjaro-browsers-pipemenu
@@ -16,8 +16,8 @@ FAIL_MSG="No Apps Installed"
 CMD=(chromium chromium-snapshot-bin firefox firefox-developer-edition google-chrome-stable opera qutebrowser vivaldi vivaldi-snapshot)
 DESC=(Chromium "Chromium Snapshot" Firefox "Firefox-Dev" "Google Chrome" Opera qutebrowser Vivaldi "Vivaldi-Snapshot")
 # source lib file
-if ! . "/usr/lib/manjaro-openbox/common/manjaro-include.cfg" 2> /dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro-openbox/common/manjaro-include.cfg"
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
     exit 1
 fi
 
diff --git a/scripts/manjaro-editors-pipemenu b/scripts/manjaro-editors-pipemenu
--- a/scripts/manjaro-editors-pipemenu
+++ b/scripts/manjaro-editors-pipemenu
@@ -17,8 +17,8 @@ CMD=(atom brackets emacs geany gedit gvim leafpad mousepad vscode subl3)
 DESC=(Atom Brackets Emacs Geany Gedit Gvim Leafpad Mousepad "Visual Studio" Sublime)
 
 # source lib file
-if ! . "/usr/lib/manjaro-openbox/common/manjaro-include.cfg" 2> /dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro-openbox/common/manjaro-include.cfg"
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
     exit 1
 fi
 
diff --git a/scripts/manjaro-graphics-pipemenu b/scripts/manjaro-graphics-pipemenu
--- a/scripts/manjaro-graphics-pipemenu
+++ b/scripts/manjaro-graphics-pipemenu
@@ -17,8 +17,8 @@ CMD=(gimp inkscape kdenlive krita openshot pinta gpicview gpick)
 DESC=(Gimp Inkscape Kdenlive Krita Openshot Pinta "Picture Viewer" Gpick)
 
 # source lib file
-if ! . "/usr/lib/manjaro-openbox/common/manjaro-include.cfg" 2> /dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro-openbox/common/manjaro-include.cfg"
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
     exit 1
 fi
 
diff --git a/scripts/manjaro-media-pipemenu b/scripts/manjaro-media-pipemenu
--- a/scripts/manjaro-media-pipemenu
+++ b/scripts/manjaro-media-pipemenu
@@ -17,8 +17,8 @@ CMD=(audacious clementine guvcview lollypop rhythmbox spotify vlc mpv gnome-mpv 
 DESC=(Audacious "Clementine Music Player" guvcview Lollypop Rhythmbox Spotify VLC MPV Gnome-MPV Sonata Cantata)
 
 # source lib file
-if ! . "/usr/lib/manjaro-openbox/common/manjaro-include.cfg" 2> /dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro-openbox/common/manjaro-include.cfg"
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
     exit 1
 fi
 
diff --git a/scripts/manjaro-office-pipemenu b/scripts/manjaro-office-pipemenu
--- a/scripts/manjaro-office-pipemenu
+++ b/scripts/manjaro-office-pipemenu
@@ -17,8 +17,8 @@ CMD=(abiword calligra epdfview libreoffice mupdf qpdfview zathura)
 DESC=(Abiword "Calligra Suite" ePDFview "Libre Office" muPDF qpdfview Zathura)
 
 # source lib file
-if ! . "/usr/lib/manjaro-openbox/common/manjaro-include.cfg" 2> /dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro-openbox/common/manjaro-include.cfg"
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
     exit 1
 fi
 
diff --git a/scripts/manjaro-settings-pipemenu b/scripts/manjaro-settings-pipemenu
--- a/scripts/manjaro-settings-pipemenu
+++ b/scripts/manjaro-settings-pipemenu
@@ -23,8 +23,8 @@ DESC=("Panel Chooser" "Screen Settings" Wallpaper Oomox "Package Manager"
       )
 
 # source lib file
-if ! . "/usr/lib/manjaro-openbox/common/manjaro-include.cfg" 2> /dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro-openbox/common/manjaro-include.cfg"
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
     exit 1
 fi
 
