added scripts and skel

diff --git a/scripts/manjaro-compositor b/scripts/manjaro-compositor
--- a/scripts/manjaro-compositor
+++ b/scripts/manjaro-compositor
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-# al-compositor: an Openbox Pipe Menu for use with compton compositor
+# manjaro-compositor: an Openbox Pipe Menu for use with compton compositor
 # Copyright (C) 2012 Philip Newborough <corenominal@corenominal.org>
 # Copyright (C) 2013 Aleks-Daniel Jakimenko
 # Copyright (C) 2015 John Crawley <john@bunsenlabs.org>
@@ -8,7 +8,7 @@
 readonly EXECXCOMP='compton -b'
 readonly RESTART_ATTEMPTS=20
 readonly HELP='
-al-compositor an openbox pipe menu for use with compton
+manjaro-compositor an openbox pipe menu for use with compton
 It should normally be called from an openbox menu.
 
 Options (passed from the menu):
@@ -19,7 +19,7 @@ Options (passed from the menu):
     --edit      open the compton config file in a text editor
     --watch     restart compton when the config is modified (useful for debugging)
 
-If al-compositor is called with no options (the usual method),
+If manjaro-compositor is called with no options (the usual method),
 it will output an xml openbox pipemenu for handling compositing.
 
 See ~/.config/compton.conf and "man compton" for configuration options.'
@@ -30,8 +30,8 @@ for i in "$@"; do
     esac
 done
 
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
-    echo $"Error: Failed to source /usr/lib/manjaro/common/al-include.cfg" >&2 ; exit 1
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
+    echo $"Error: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg" >&2 ; exit 1
 fi
 
 declareDependencies compton
diff --git a/scripts/manjaro-conky-pipemenu b/scripts/manjaro-conky-pipemenu
--- a/scripts/manjaro-conky-pipemenu
+++ b/scripts/manjaro-conky-pipemenu
@@ -1,20 +1,20 @@
 #!/usr/bin/env bash
 
-# al-conky-pipemenu - an Openbox pipemenu for manipulating conky
+# manjaro-conky-pipemenu - an Openbox pipemenu for manipulating conky
 # Copyright (C) 2015 damo <damo@bunsenlabs.org>
 
-readonly CZEN="al-conkyzen"
-readonly CSESSION="al-conky-session"
+readonly CZEN="manjaro-conkyzen"
+readonly CSESSION="manjaro-conky-session"
 readonly CONKYDEFAULT="$HOME/.config/conky/Manjaro.conkyrc"
 readonly CONKYPATH="$HOME/.config/conky"
 readonly CSESSIONFILE="$CONKYPATH/conky-sessionfile"
 readonly SESSIONS="$CONKYPATH/saved-sessions"
 readonly HELPFILE="/usr/share/manjaro/docs/helpfile-conkyzen.txt"
-readonly HELP='\tal-conky-pipemenu an Openbox Pipe Menu for use with conky
+readonly HELP='\tmanjaro-conky-pipemenu an Openbox Pipe Menu for use with conky
 \tIt should normally be called from an openbox menu.
 \nOptions:
 \t-h --help   show this message
-\n\tIf al-conky-pipemenu is called with no options (the usual method),
+\n\tIf manjaro-conky-pipemenu is called with no options (the usual method),
 \tit will output an xml openbox pipemenu for handling conky sessions.
 \nSee /usr/share/manjaro/docs/helpfile-conkyzen.txt and "man conky" for more information'
 
@@ -24,8 +24,8 @@ for arg in "$@"; do
     esac
 done
 
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
-    echo "Error: Failed to source /usr/lib/manjaro/common/al-include.cfg" ; exit 1
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
+    echo "Error: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg" ; exit 1
 fi
 
 if ! [[ -e $CSESSIONFILE ]]; then
@@ -76,8 +76,8 @@ loadSavedsessionSubmenu(){
 }
 
 loadPinMenu(){
-    if type al-conkypin &>/dev/null; then
-        menuItem "Pin moveable Conkys" "al-conkypin"
+    if type manjaro-conkypin &>/dev/null; then
+        menuItem "Pin moveable Conkys" "manjaro-conkypin"
         menuSeparator
     fi
 }
@@ -108,8 +108,8 @@ loadEditMenu(){
 
 getConkys(){
     menuSubmenu "EditConky" "Edit Conkys"
-    if type al-conkyedit &>/dev/null;then
-        menuItem "Conky Editor" "al-conkyedit"
+    if type manjaro-conkyedit &>/dev/null;then
+        menuItem "Conky Editor" "manjaro-conkyedit"
         loadEditMenu
     else
         loadEditMenu
diff --git a/scripts/manjaro-editors-pipemenu b/scripts/manjaro-editors-pipemenu
--- a/scripts/manjaro-editors-pipemenu
+++ b/scripts/manjaro-editors-pipemenu
@@ -4,7 +4,7 @@
 # written by Nathaniel Maia, December 2017
 
 # Add something like this to your menu.xml
-# <menu execute="al-code-pipemenu" id="code" label="Code"/>
+# <menu execute="manjaro-code-pipemenu" id="code" label="Code"/>
 
 NAME="code"
 PNAME="Code"
@@ -14,8 +14,8 @@ CMD=(atom brackets emacs geany gedit gvim leafpad mousepad vscode subl3)
 DESC=(Atom Brackets Emacs Geany Gedit Gvim Leafpad Mousepad "Visual Studio" Sublime)
 
 # source lib file
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg"
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
     exit 1
 fi
 
@@ -39,8 +39,8 @@ else
     menuSeparator "$FAIL_MSG"
     if hash pamac-manager &>/dev/null; then
         menuItem "Install with Package Manager" "pamac-manager"
-    elif hash termite pacli &>/dev/null; then
-        menuItem "Install with Package Manager" "termite -e pacli"
+    elif hash termite pacui &>/dev/null; then
+        menuItem "Install with Package Manager" "termite -e pacui"
     fi
 fi
 menuEnd
diff --git a/scripts/manjaro-games-pipemenu b/scripts/manjaro-games-pipemenu
--- a/scripts/manjaro-games-pipemenu
+++ b/scripts/manjaro-games-pipemenu
@@ -15,8 +15,8 @@ CMD=(minecraft minetest lsi-steam steam-runtime 0ad gnome-games
 DESC=(Minecraft Minetest Steam "Steam Runtime" 0AD "Gnome Games"
       Aisleriot Hitori Chromium  "Gnu Chess" "Gnome Chess")
 
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg"
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
     exit 1
 fi
 
@@ -40,8 +40,8 @@ else
     menuSeparator "$FAIL_MSG"
     if hash pamac-manager &>/dev/null; then
         menuItem "Install with Package Manager" "pamac-manager"
-    elif hash termite pacli &>/dev/null; then
-        menuItem "Install with Package Manager" "termite -e pacli"
+    elif hash termite pacui &>/dev/null; then
+        menuItem "Install with Package Manager" "termite -e pacui"
     fi
 fi
 menuEnd
diff --git a/scripts/manjaro-graphics-pipemenu b/scripts/manjaro-graphics-pipemenu
--- a/scripts/manjaro-graphics-pipemenu
+++ b/scripts/manjaro-graphics-pipemenu
@@ -4,7 +4,7 @@
 # written by Nathaniel Maia, December 2017
 
 # Add something like this to your menu.xml
-# <menu execute="al-graphics-pipemenu" id="graphics" label="Graphics"/>
+# <menu execute="manjaro-graphics-pipemenu" id="graphics" label="Graphics"/>
 
 NAME="graphics"
 PNAME="Graphics"
@@ -17,8 +17,8 @@ DESC=(Gimp Inkscape "OBS Studio" SimpleScreenRecorder Kdenlive Krita Openshot Pi
       Viewnior "Picture Viewer" Gpick Gcolor2 "Xfce Screenshooter"
       )
 
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg"
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
     exit 1
 fi
 
@@ -42,8 +42,8 @@ else
     menuSeparator "$FAIL_MSG"
     if hash pamac-manager &>/dev/null; then
         menuItem "Install with Package Manager" "pamac-manager"
-    elif hash termite pacli &>/dev/null; then
-        menuItem "Install with Package Manager" "termite -e pacli"
+    elif hash termite pacui &>/dev/null; then
+        menuItem "Install with Package Manager" "termite -e pacui"
     fi
 fi
 menuEnd
diff --git a/scripts/manjaro-help-pipemenu b/scripts/manjaro-help-pipemenu
--- a/scripts/manjaro-help-pipemenu
+++ b/scripts/manjaro-help-pipemenu
@@ -1,15 +1,15 @@
 #!/usr/bin/env bash
 
-# al-help-pipemenu - an Openbox pipemenu for displaying help files
+# manjaro-help-pipemenu - an Openbox pipemenu for displaying help files
 
 readonly HELP='
-al-help-pipemenu an Openbox Pipe Menu for displaying help files
+manjaro-help-pipemenu an Openbox Pipe Menu for displaying help files
 It should normally be called from an openbox menu.
 
 Options (usually passed from the menu):
     -h --help   show this message
 
-If al-help-pipemenu is called with no options (the usual method),
+If manjaro-help-pipemenu is called with no options (the usual method),
 it will output an xml openbox pipemenu displaying various help links,
 '
 for i in "$@"; do
@@ -18,21 +18,15 @@ for i in "$@"; do
     esac
 done
 
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
-    echo $"Error: Failed to source /usr/lib/manjaro/common/al-include.cfg" >&2 ; exit 1
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
+    echo $"Error: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg" >&2 ; exit 1
 fi
 
 menuStart
-menuSeparator 'ARCHLABS LINUX ONLINE'
-menuItem 'Manjaro Homepage' 'exo-open "https://www.manjarolinux.com/"'
-menuItem 'Manjaro Reddit' 'exo-open "https://www.reddit.com/r/ManjaroLinux/"'
-menuItem 'Manjaro Forum' 'exo-open "https://forum.manjarolinux.com/"'
-menuItem 'Manjaro Google+' 'exo-open "https://plus.google.com/u/0/communities/111177505820810068511"'
-menuItem 'Manjaro Knowledge Base' 'exo-open "https://manjaro-knowledge-base.gitbooks.io/knowledge_base/content/"'
-
-menuSeparator 'ARCHLABS LINUX HELP'
-menuItem 'Forum Basic Help & Support' 'exo-open "https://forum.manjarolinux.com/c/newbie-corner"'
-menuItem 'Scripts, Tutorials & Tips' 'exo-open "https://forum.manjarolinux.com/c/configs-scripts-tutorials-tips"'
+menuSeparator 'MANJARO LINUX ONLINE'
+menuItem 'Manjaro Homepage' 'exo-open "https://www.manjaro.org/"'
+menuItem 'Manjaro Forum' 'exo-open "https://forum.manjar.org/"'
+menuItem 'Manjaro Wiki' 'exo-open "https://wiki.manjaro.org/"'
 
 menuSeparator 'GUIDES'
 
diff --git a/scripts/manjaro-kb-pipemenu b/scripts/manjaro-kb-pipemenu
--- a/scripts/manjaro-kb-pipemenu
+++ b/scripts/manjaro-kb-pipemenu
@@ -1,15 +1,15 @@
 #!/usr/bin/env bash
 
-# al-kb-pipemenu - an Openbox pipemenu for displaying keybinds
+# manjaro-kb-pipemenu - an Openbox pipemenu for displaying keybinds
 # Copyright (C) 2015 damo <damo@bunsenlabs.org>
 # Copyright (C) 2018 Nathaniel Maia  <natemaia10@gmail.com>
 # Renamed and rewritten for Manjaro and zenity
 
-readonly KBSCRIPT="al-kb"
+readonly KBSCRIPT="manjaro-kb"
 readonly CFG_DIR="$HOME/.config/openbox"
 readonly RCPATH="$CFG_DIR/rc.xml"
 readonly KBTEXT="$CFG_DIR/kbinds.txt"
-readonly HELP='\tal-kb-pipemenu an Openbox Pipe Menu for displaying keybinds
+readonly HELP='\tmanjaro-kb-pipemenu an Openbox Pipe Menu for displaying keybinds
 \tIt should normally be called from an openbox menu.
 \nOptions (usually passed from the menu):
 \t-h --help   show this message
@@ -17,17 +17,17 @@ readonly HELP='\tal-kb-pipemenu an Openbox Pipe Menu for displaying keybinds
 \t(The keybinds in the menu are clickable, except for the Openbox
 \tcommands, which just exit the menu.)
 \t--rcedit    backup and edit rc.xml
-\nIf al-keyboard-pipemenu is called with no options (the usual method),
+\nIf manjaro-keyboard-pipemenu is called with no options (the usual method),
 it will output an xml openbox pipemenu for displaying keybindings.
 \tNOTE: Some of the functionality of this pipemenu depends on the script
-/usr/bin/al-kb which is provided by the package "manjaro-utilities"'
+/usr/bin/manjaro-kb which is provided by the package "manjaro-utilities"'
 
 case "$@" in
     -h|--help) echo -e "$HELP" ; exit 0
 esac
 
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate /usr/lib/manjaro/common//al-include.cfg" >&2
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to locate /usr/lib/manjaro/common//manjaro-include.cfg" >&2
     exit 1
 fi
 
@@ -74,10 +74,10 @@ if [[ $1 = '--keybinds' ]]; then
 fi
 
 menuStart
-    menuItem "Backup and Edit rc.xml" "al-kb-pipemenu --rcedit"
+    menuItem "Backup and Edit rc.xml" "manjaro-kb-pipemenu --rcedit"
     menuSeparator
-    menuItem "Display Keybinds in window" "al-kb --gui"
-    echo '        <menu execute="al-kb-pipemenu --keybinds" id="Display keybinds" label="Display Keybinds in menu"/>'
+    menuItem "Display Keybinds in window" "manjaro-kb --gui"
+    echo '        <menu execute="manjaro-kb-pipemenu --keybinds" id="Display keybinds" label="Display Keybinds in menu"/>'
 menuEnd
 
 exit 0
diff --git a/scripts/manjaro-media-pipemenu b/scripts/manjaro-media-pipemenu
--- a/scripts/manjaro-media-pipemenu
+++ b/scripts/manjaro-media-pipemenu
@@ -17,8 +17,8 @@ DESC=(Audacity Audacious DeaDBeeF Clementine guvcview Lollypop
       "Gnome Music" Rhythmbox Spotify VLC MPV Gnome-MPV Sonata Cantata
       Kodi)
 
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg"
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
     exit 1
 fi
 
@@ -46,8 +46,8 @@ else
     menuSeparator "$FAIL_MSG"
     if hash pamac-manager &>/dev/null; then
         menuItem "Install with Package Manager" "pamac-manager"
-    elif hash termite pacli &>/dev/null; then
-        menuItem "Install with Package Manager" "termite -e pacli"
+    elif hash termite pacui &>/dev/null; then
+        menuItem "Install with Package Manager" "termite -e pacui"
     fi
 fi
 menuEnd
diff --git a/scripts/manjaro-office-pipemenu b/scripts/manjaro-office-pipemenu
--- a/scripts/manjaro-office-pipemenu
+++ b/scripts/manjaro-office-pipemenu
@@ -4,7 +4,7 @@
 # written by Nathaniel Maia, December 2017 for Manjaro
 
 # Add something like this to your menu.xml
-# <menu execute="al-office-pipemenu" id="office" label="Office"/>
+# <menu execute="manjaro-office-pipemenu" id="office" label="Office"/>
 
 NAME="office"
 PNAME="Office"
@@ -13,8 +13,8 @@ FAIL_MSG="No Apps Installed"
 CMD=(abiword calligra epdfview galculator libreoffice mupdf qpdfview zathura)
 DESC=(Abiword "Calligra Suite" ePDFview Calculator "Libre Office" muPDF qpdfview Zathura)
 
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg"
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
     exit 1
 fi
 
@@ -38,8 +38,8 @@ else
     menuSeparator "$FAIL_MSG"
     if hash pamac-manager &>/dev/null; then
         menuItem "Install with Package Manager" "pamac-manager"
-    elif hash termite pacli &>/dev/null; then
-        menuItem "Install with Package Manager" "termite -e pacli"
+    elif hash termite pacui &>/dev/null; then
+        menuItem "Install with Package Manager" "termite -e pacui"
     fi
 fi
 menuEnd
diff --git a/scripts/manjaro-polybar-pipemenu b/scripts/manjaro-polybar-pipemenu
--- a/scripts/manjaro-polybar-pipemenu
+++ b/scripts/manjaro-polybar-pipemenu
@@ -1,15 +1,15 @@
 #!/usr/bin/env bash
 
-# al-polybar-pipemenu - an Openbox pipemenu for polybar manipulation
+# manjaro-polybar-pipemenu - an Openbox pipemenu for polybar manipulation
 # Written for Manjaro by Nathaniel Maia <natemaaia10@gmail.com> 2017
 
 readonly CPATH="$HOME/.config/polybar"
 readonly HELP='
-\tal-polybar-pipemenu an Openbox Pipe Menu for Polybar
+\tmanjaro-polybar-pipemenu an Openbox Pipe Menu for Polybar
 \tIt should normally be called from an openbox menu.
 \nOptions:
 \t-h --help   show this message
-\n\tIf al-polybar-pipemenu is called with no options (the usual method),
+\n\tIf manjaro-polybar-pipemenu is called with no options (the usual method),
 \tit will output an xml openbox pipemenu for handling polybar sessions,
 \tand editing configuration files.
 \nFor more information, see "man polybar"
@@ -20,8 +20,8 @@ case "$@" in
 esac
 
 CONFIG="$CPATH/config"
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
-    echo $"Error: Failed to source /usr/lib/manjaro/common/al-include.cfg" ; exit 1
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
+    echo $"Error: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg" ; exit 1
 fi
 
 Editmenu() {
@@ -50,23 +50,23 @@ Editmenu() {
 
 Configs() {
     menuSubmenu "EditConfigs" "Edit Configs"
-    if hash al-polybar-edit &>/dev/null; then
-        menuItem "Edit Configs" "al-polybar-edit"
+    if hash manjaro-polybar-edit &>/dev/null; then
+        menuItem "Edit Configs" "manjaro-polybar-edit"
     fi
     Editmenu
     menuSubmenuEnd
 }
 
 Launchmenu() {
-    if hash al-polybar-session &>/dev/null && [[ -f "$CPATH/sessions/openbox-sessionfile" ]]; then
+    if hash manjaro-polybar-session &>/dev/null && [[ -f "$CPATH/sessions/openbox-sessionfile" ]]; then
         if [[ $(pidof polybar) ]]; then
-            menuItem "Restart Polybar" "al-polybar-session"
+            menuItem "Restart Polybar" "manjaro-polybar-session"
         else
-            menuItem "Start Polybar" "al-polybar-session"
+            menuItem "Start Polybar" "manjaro-polybar-session"
         fi
     fi
-    if type al-polyzen &>/dev/null; then
-        menuItem "Polybar GUI" "al-polyzen"
+    if type manjaro-polyzen &>/dev/null; then
+        menuItem "Polybar GUI" "manjaro-polyzen"
     fi
 }
 
diff --git a/scripts/manjaro-settings-pipemenu b/scripts/manjaro-settings-pipemenu
--- a/scripts/manjaro-settings-pipemenu
+++ b/scripts/manjaro-settings-pipemenu
@@ -10,15 +10,15 @@ NAME="settings"
 PNAME="Settings"
 FAIL_MSG="No Apps Installed"
 
-CMD=(al-panel-chooser arandr nitrogen oomox-gui pamac-manager pavucontrol
+CMD=(manjaro-panel-chooser arandr nitrogen oomox-gui pamac-manager pavucontrol
      gnome-system-monitor wpg rofi-theme-selector xfce4-power-manager-settings
      gnome-disk-utility xfce4-appearance-settings xfce4-settings-manager lxappearance)
 DESC=("Panel Chooser" "Screen Settings" Wallpaper Oomox "Package Manager"
       "Audio Settings" "System Monitor" wpgtk "Rofi Theme" "Power Manager"
       "Disk Uitlity" "Gtk Theme" "Settings Manager" LXappearance)
 
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg" ; exit 1
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg" ; exit 1
 fi
 
 menu_Body() {
diff --git a/scripts/manjaro-system-pipemenu b/scripts/manjaro-system-pipemenu
--- a/scripts/manjaro-system-pipemenu
+++ b/scripts/manjaro-system-pipemenu
@@ -15,8 +15,8 @@ CMD=(gparted nvidia-settings flash.sh etcher mintstick grub-customizer pacli pam
 DESC=(Gparted Nvidia "Flash USB" Etcher Mintstick "Grub Customizer" "Package Manager" "Pamac Manager"
       "Root File Mananger" "Root Terminal")
 
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
-    echo "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg" ; exit 1
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
+    echo "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg" ; exit 1
 fi
 
 menu_Body() {
diff --git a/scripts/manjaro-terminal-pipemenu b/scripts/manjaro-terminal-pipemenu
--- a/scripts/manjaro-terminal-pipemenu
+++ b/scripts/manjaro-terminal-pipemenu
@@ -10,12 +10,12 @@ NAME="terminals"
 PNAME="Terminals"
 FAIL_MSG="No Apps Installed"
 
-CMD=(terminator tilda tilix urxvt st termite xfce4-terminal xterm)
+CMD=(terminator tilda tilix urxvt st termite xfce4-terminal xterm lxterminal)
 DESC=(Terminator Tilda Tilix Rxvt-Unicode "Suckless Terminal" Termite
-      Xfce4-terminal Xterm)
+      Xfce4-terminal Xterm "LX Terminal")
 
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg" ; exit 1
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg" ; exit 1
 fi
 
 menu_Body() {
@@ -38,8 +38,8 @@ else
     menuSeparator "$FAIL_MSG"
     if hash pamac-manager &>/dev/null; then
         menuItem "Install with Package Manager" "pamac-manager"
-    elif hash termite pacli &>/dev/null; then
-        menuItem "Install with Package Manager" "termite -e pacli"
+    elif hash termite pacui &>/dev/null; then
+        menuItem "Install with Package Manager" "termite -e pacui"
     fi
 fi
 menuEnd
diff --git a/scripts/manjaro-tint2-pipemenu b/scripts/manjaro-tint2-pipemenu
--- a/scripts/manjaro-tint2-pipemenu
+++ b/scripts/manjaro-tint2-pipemenu
@@ -1,19 +1,19 @@
 #!/usr/bin/env bash
 
-# al-tint2-pipemenu - an Openbox pipemenu for tint2 manipulation
+# manjaro-tint2-pipemenu - an Openbox pipemenu for tint2 manipulation
 # Copyright (C) 2015-2016 damo
 # Borrowed with love by the Manjaro boys.
 
-readonly TZEN="al-tint2zen"
+readonly TZEN="manjaro-tint2zen"
 readonly TINT2RC="$HOME/.config/tint2/tint2rc"
 readonly HELP='
-al-tint2-pipemenu an Openbox Pipe Menu for tint2 manipulation
+manjaro-tint2-pipemenu an Openbox Pipe Menu for tint2 manipulation
 It should normally be called from an openbox menu.
 
 Options:
     -h --help   show this message
 
-If al-tint2-pipemenu is called with no options (the usual method),
+If manjaro-tint2-pipemenu is called with no options (the usual method),
 it will output an xml openbox pipemenu for handling tint2 sessions,
 and editing configuration files.
 
@@ -24,8 +24,8 @@ case "$@" in
     -h|--help) echo "$HELP" ; exit 0
 esac
 
-if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
-    echo $"Error: Failed to source /usr/lib/manjaro/al-include.cfg" >&2
+if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2>/dev/null; then
+    echo $"Error: Failed to source /usr/lib/manjaro/manjaro-include.cfg" >&2
     exit 1
 fi
 
@@ -59,8 +59,8 @@ loadTEditmenu() {
 
 getTint2s() {
     menuSubmenu "EditTint2" "Edit Tint2s"
-        if type al-tint2edit &>/dev/null; then
-            menuItem "Tint2 Editor" "al-tint2edit"
+        if type manjaro-tint2edit &>/dev/null; then
+            menuItem "Tint2 Editor" "manjaro-tint2edit"
         fi
         loadTEditmenu
     menuSubmenuEnd
@@ -74,8 +74,8 @@ loadChoosermenu() {
 
 loadRestartmenu() {
     if [[ $(pidof tint2) ]];then
-        if type al-tint2restart &>/dev/null; then
-            menuItem "Restart Tint2" "al-tint2restart"
+        if type manjaro-tint2restart &>/dev/null; then
+            menuItem "Restart Tint2" "manjaro-tint2restart"
         fi
         menuItem "Stop Tint2s" "pkill tint2"
     fi
