updated - renamed to common

diff --git a/scripts/manjaro-browsers-pipemenu b/scripts/manjaro-browsers-pipemenu
--- a/scripts/manjaro-browsers-pipemenu
+++ b/scripts/manjaro-browsers-pipemenu
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 
-
 # A pipemenu base script/template for creating category based pipemenus
 # written by Nathaniel Maia, December 2017 for Manjaro
 
@@ -11,13 +10,15 @@ NAME="browsers"
 PNAME="Browsers"
 FAIL_MSG="No Apps Installed"
 
-# make sure these two arrays are the same amount of items
-# if not things will go wrong and you will have blank space
-CMD=(chromium chromium-snapshot-bin firefox firefox-developer-edition google-chrome-stable opera qutebrowser vivaldi vivaldi-snapshot)
-DESC=(Chromium "Chromium Snapshot" Firefox "Firefox-Dev" "Google Chrome" Opera qutebrowser Vivaldi "Vivaldi-Snapshot")
-# source lib file
-if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
+CMD=(chromium chromium-snapshot-bin firefox firefox-developer-edition
+     google-chrome-stable opera qutebrowser vivaldi vivaldi-snapshot
+     )
+DESC=(Chromium "Chromium Snapshot" Firefox "Firefox-Dev"
+      "Google Chrome" Opera qutebrowser Vivaldi "Vivaldi-Snapshot"
+      )
+
+if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg"
     exit 1
 fi
 
@@ -30,14 +31,20 @@ menu_Body() {
 }
 
 menuStart "$NAME" "$PNAME"
-num=0
 for x in "${CMD[@]}"; do
-    if hash "$x" &>/dev/null; then num=$((num + 1)); fi
+    if hash "$x" &>/dev/null; then
+        num=1 ; break
+    fi
 done
 if [[ $num -gt 0 ]]; then
     menu_Body
 else
     menuSeparator "$FAIL_MSG"
+    if hash pamac-manager &>/dev/null; then
+        menuItem "Install with Package Manager" "pamac-manager"
+    elif hash termite pacli &>/dev/null; then
+        menuItem "Install with Package Manager" "termite -e pacli"
+    fi
 fi
 menuEnd
 
diff --git a/scripts/manjaro-compositor b/scripts/manjaro-compositor
--- a/scripts/manjaro-compositor
+++ b/scripts/manjaro-compositor
@@ -1,70 +1,46 @@
 #!/usr/bin/env bash
 
-#    manjaro-compositor: an Openbox Pipe Menu for use with compton compositor
-#    Copyright (C) 2012 Philip Newborough   <corenominal@corenominal.org>
-#    Copyright (C) 2013 Aleks-Daniel Jakimenko
-#    Copyright (C) 2015 John Crawley    <john@bunsenlabs.org>
-#
-#    This program is free software: you can redistribute it and/or modify
-#    it under the terms of the GNU General Public License as published by
-#    the Free Software Foundation, either version 3 of the License, or
-#    (at your option) any later version.
-#
-#    This program is distributed in the hope that it will be useful,
-#    but WITHOUT ANY WARRANTY; without even the implied warranty of
-#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#    GNU General Public License for more details.
-#
-#    You should have received a copy of the GNU General Public License
-#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# al-compositor: an Openbox Pipe Menu for use with compton compositor
+# Copyright (C) 2012 Philip Newborough <corenominal@corenominal.org>
+# Copyright (C) 2013 Aleks-Daniel Jakimenko
+# Copyright (C) 2015 John Crawley <john@bunsenlabs.org>
 
+readonly EXECXCOMP='compton -b'
+readonly RESTART_ATTEMPTS=20
+readonly HELP='
+al-compositor an openbox pipe menu for use with compton
+It should normally be called from an openbox menu.
 
-EXECXCOMP='compton -b'
-RESTART_ATTEMPTS=20
-MANJARO_COMMON_LIBDIR='/usr/lib/manjaro/common'
-HELP='    manjaro-compositor an Openbox Pipe Menu for use with compton compositor
-    It should normally be called from an openbox menu.
-
-Options (usually passed from the menu):
+Options (passed from the menu):
     -h --help   show this message
     --start     start the compositor and restart tint2, if running
     --restart   restart the compositor, if running
     --stop      stop the compositor
     --edit      open the compton config file in a text editor
-    --watch     restart the compositor whenever the config file is modified
-    (--watch is useful for debugging)
+    --watch     restart compton when the config is modified (useful for debugging)
 
-    If manjaro-compositor is called with no options (the usual method),
-    it will output an xml openbox pipemenu for handling compositing.
+If al-compositor is called with no options (the usual method),
+it will output an xml openbox pipemenu for handling compositing.
 
-See ~/.config/compton.conf and "man compton" for configuration options.
-'
-# look for a help option somewhere
+See ~/.config/compton.conf and "man compton" for configuration options.'
+
 for i in "$@"; do
     case "$i" in
-        -h|--help)
-            echo "$HELP"
-            exit 0
-            ;;
+        -h|--help) echo "$HELP" ; exit 0
     esac
 done
 
-if ! . "$MANJARO_COMMON_LIBDIR/manjaro-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source manjaro-include.cfg in $MANJARO_COMMON_LIBDIR" >&2
-    exit 1
+if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
+    echo $"Error: Failed to source /usr/lib/manjaro/common/al-include.cfg" >&2 ; exit 1
 fi
 
 declareDependencies compton
 
 forcekill_compton() {
     killall -q compton
-    for (( i=0; i < RESTART_ATTEMPTS; i++ )); do
-        pidof compton > /dev/null ||
-            break
-
-        (( i == RESTART_ATTEMPTS - 1 )) &&
-            killall -q -S KILL compton
-
+    for ((i=0; i<RESTART_ATTEMPTS; i++)); do
+        [[ $(pidof compton) ]] || break
+        killall -q -S KILL compton
         sleep 0.25
     done
 }
@@ -90,7 +66,7 @@ elif [[ $1 = '--stop' ]]; then
     forcekill_compton
 
 elif [[ $1 = '--restart' ]]; then
-    if pidof compton > /dev/null; then
+    if [[ $(pidof compton) ]]; then
         forcekill_compton
         "$0" --start
     else # nothing to restart
diff --git a/scripts/manjaro-conky-pipemenu b/scripts/manjaro-conky-pipemenu
--- a/scripts/manjaro-conky-pipemenu
+++ b/scripts/manjaro-conky-pipemenu
@@ -1,52 +1,39 @@
 #!/usr/bin/env bash
 
-#    manjaro-conky-pipemenu - an Openbox pipemenu for manipulating conky
-#    Copyright (C) 2015 damo <damo@bunsenlabs.org>
-#
-#    This program is free software: you can redistribute it and/or modify
-#    it under the terms of the GNU General Public License as published by
-#    the Free Software Foundation, either version 3 of the License, or
-#    (at your option) any later version.
-#
-#    This program is distributed in the hope that it will be useful,
-#    but WITHOUT ANY WARRANTY; without even the implied warranty of
-#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#    GNU General Public License for more details.
-#
-#    You should have received a copy of the GNU General Public License
-#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# al-conky-pipemenu - an Openbox pipemenu for manipulating conky
+# Copyright (C) 2015 damo <damo@bunsenlabs.org>
 
-MANJARO_COMMON_LIBDIR='/usr/lib/manjaro/common'
-CONKYDEFAULT="$HOME/.config/conky/Manjaro.conkyrc"
-CONKYPATH="$HOME/.config/conky"
-CSESSIONFILE="$CONKYPATH/conky-sessionfile"
-SESSIONS="$CONKYPATH/saved-sessions"
-CZEN="manjaro-conkyzen"
-CSESSION="manjaro-conky-session"
-HELPFILE="/usr/share/manjaro/docs/helpfile-conkyzen.txt"
-HELP='\tmanjaro-conky-pipemenu an Openbox Pipe Menu for use with conky
+readonly CZEN="al-conkyzen"
+readonly CSESSION="al-conky-session"
+readonly CONKYDEFAULT="$HOME/.config/conky/Manjaro.conkyrc"
+readonly CONKYPATH="$HOME/.config/conky"
+readonly CSESSIONFILE="$CONKYPATH/conky-sessionfile"
+readonly SESSIONS="$CONKYPATH/saved-sessions"
+readonly HELPFILE="/usr/share/manjaro/docs/helpfile-conkyzen.txt"
+readonly HELP='\tal-conky-pipemenu an Openbox Pipe Menu for use with conky
 \tIt should normally be called from an openbox menu.
 \nOptions:
 \t-h --help   show this message
-tIf manjaro-conky-pipemenu is called with no options (the usual method),
-tit will output an xml openbox pipemenu for handling conky sessions.
-\nSee /usr/share/manjaro/docs/helpfile-conkyzen.txt and "man conky"
-for more information'
-case "$@" in
-    -h|--help)
-        echo -e "$HELP"
-        exit 0
-esac
+\n\tIf al-conky-pipemenu is called with no options (the usual method),
+\tit will output an xml openbox pipemenu for handling conky sessions.
+\nSee /usr/share/manjaro/docs/helpfile-conkyzen.txt and "man conky" for more information'
 
-if ! . "$MANJARO_COMMON_LIBDIR/manjaro-include.cfg" &>/dev/null; then
-    echo "Error: Failed to source manjaro-include.cfg in $MANJARO_COMMON_LIBDIR"
-    exit 1
+for arg in "$@"; do
+    case $arg in
+        -h|--help) echo -e "$HELP" ; exit 0
+    esac
+done
+
+if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
+    echo "Error: Failed to source /usr/lib/manjaro/common/al-include.cfg" ; exit 1
 fi
-if [ ! -e "$CSESSIONFILE" ] &>/dev/null ; then
+
+if ! [[ -e $CSESSIONFILE ]]; then
     echo "Error: Failed to locate conky-sessionfile in $CONKYPATH" >&2
-    echo "conky -c $HOME/.config/conky/AL-Default.conkyrc & sleep 1" > "$CSESSIONFILE"
+    echo "conky -c $CONKYPATH/Manjaro.conkyrc & sleep 1" > "$CSESSIONFILE"
 fi
-if [ ! -e "$SESSIONS" ] &>/dev/null ; then
+
+if ! [[ -e $SESSIONS ]]; then
     echo "$0: Failed to locate saved-sessions in $CONKYPATH" >&2
 fi
 
@@ -54,7 +41,7 @@ declareDependencies zenity
 
 getSessions(){
     menuItem "Default" "$CSESSION $CSESSIONFILE"
-    if [ -e "$SESSIONS" ]; then
+    if [[ -e $SESSIONS ]]; then
         while read -r session ; do
             [[ -z $session ]] && continue
             menuItem "$session" "$CSESSION $session"
@@ -89,8 +76,8 @@ loadSavedsessionSubmenu(){
 }
 
 loadPinMenu(){
-    if type manjaro-conkypin &>/dev/null; then
-        menuItem "Pin moveable Conkys" "manjaro-conkypin"
+    if type al-conkypin &>/dev/null; then
+        menuItem "Pin moveable Conkys" "al-conkypin"
         menuSeparator
     fi
 }
@@ -105,8 +92,8 @@ loadEditMenu(){
         menuSubmenu "RunningConky" "Running Conkys"
         while read -r session; do
             [[ -z $session ]] && continue
-            CPATH=$(echo "$session" | awk '{print $3}')
-            CONKY=$(echo "$CPATH" | awk -F"/" '{print $(NF-1)"/"$NF }')
+            CPATH=$(awk '{print $3}' <<< "$session")
+            CONKY=$(awk -F"/" '{print $(NF-1)"/"$NF }' <<< "$CPATH")
             if hash exo-open &>/dev/null; then
                 menuItem "$CONKY" "exo-open $CPATH"
             else
@@ -121,8 +108,8 @@ loadEditMenu(){
 
 getConkys(){
     menuSubmenu "EditConky" "Edit Conkys"
-    if type manjaro-conkyedit &>/dev/null;then
-        menuItem "Conky Editor" "manjaro-conkyedit"
+    if type al-conkyedit &>/dev/null;then
+        menuItem "Conky Editor" "al-conkyedit"
         loadEditMenu
     else
         loadEditMenu
@@ -132,7 +119,7 @@ getConkys(){
 
 checkHelpfile(){
     DLG="zenity --text-info --title='Manjaro Conky Chooser Help' --filename=$HELPFILE --width=650 --height=700 &>/dev/null"
-    if [ -e "$HELPFILE" ];then
+    if [[ -e $HELPFILE ]];then
         menuItem "Conky Chooser Help" "$DLG"
     fi
 }
diff --git a/scripts/manjaro-conkyzen b/scripts/manjaro-conkyzen
--- a/scripts/manjaro-conkyzen
+++ b/scripts/manjaro-conkyzen
@@ -1,17 +1,18 @@
 #!/usr/bin/env bash
 
-#   Manjaro Conky selection and switcher script
-#   Original concept by damo <damo@bunsenlabs.org> for BunsenLabs Linux, April 2015
-#   Beta tested and stamped "zen" by <Sector11>
-#   Rewritten by Nathaniel Maia for Manjaro, December 2017
-#
-########################################################################
+# Manjaro Conky selection and switcher script
+# Original concept by damo <damo@bunsenlabs.org> for BunsenLabs Linux, April 2015
+# Rewritten by Nathaniel Maia for Manjaro, December 2017
 
-CPATH="$HOME/.config/conky"
-SFILE="$CPATH/conky-sessionfile"
-SESSIONS="$CPATH/saved-sessions"    # to be used by a pipemenu
-DEFAULT="$CPATH/AL-Default.conkyrc"
-USAGE="\vUSAGE:\tmanjaro-conkyzen [OPTION]...FILES
+readonly CPATH="$HOME/.config/conky"
+readonly TITLE="Manjaro Conky Manager"
+readonly ICON="--window-icon=/usr/share/icons/Manjaro-Light/64x64/places/distributor-logo-archlabs.png"
+readonly INFO="zenity --info $ICON --width=200 --height=100"
+readonly QUESTION="zenity --question $ICON --width=300"
+readonly CHECKLIST="zenity $ICON --width=450 --height=500 --list --checklist --multiple"
+readonly TEXTENTRY="zenity $ICON --entry --width=350 --height=200"
+readonly MSG="<big>This session will be saved to:</big>\n\n<b>$SESSIONFILE</b>\n"
+readonly USAGE="\vUSAGE:\tal-conkyzen [OPTION]...FILES
 \v\tWith no command option the script runs the gui
 \v\t-h,--help   : this USAGE help
 \t-f,--file   : FILEPATH : specify file to save session to
@@ -21,21 +22,18 @@ USAGE="\vUSAGE:\tmanjaro-conkyzen [OPTION]...FILES
 \tcheckmarked conkys are started.
 \v\tTo stop a conky just uncheck it, and \"OK\"
 \vEXAMPLES:\n\n\tSave session to a new saved-session file with:
-\v\t\tmanjaro-conkyzen -f sessionfile-name
+\v\t\tal-conkyzen -f sessionfile-name
 \v\tTo start the default conky session at login
 \tadd the following line to autostart:
-\v\tsleep 2 && manjaro-conky-session --autostart &\v"
-QUESTION="zenity --question --window-icon=/usr/share/icons/hicolor/scalable/apps/manjaro.svg"
-TITLE="Manjaro Conky Manager"
-ICON="--window-icon=/usr/share/icons/hicolor/scalable/apps/manjaro.svg"
-FILES=($(find -L "$CPATH" -maxdepth 4 -type f))
+\v\tsleep 2 && al-conky-session --autostart &\v"
 
-
-########################### Find Conkys
+# Mutable values
+SESSIONFILE="$CPATH/conky-sessionfile"
+SESSIONS="$CPATH/saved-sessions"  # used by pipemenu
 
 if ! hash conky read find &>/dev/null; then
-    echo -e "\n[ERROR]: This script requires the following be installed
-    \n\t\t'conky'\t  'findutils'\t'readline'" && exit 2
+    echo -e "[ERROR]: This script requires the following be installed
+    \n\t\t'conky'\t  'findutils'\t'readline'" ; exit 2
 fi
 
 if ! [[ -d $CPATH ]] && [[ -d /etc/skel/.config/conky ]]; then
@@ -44,104 +42,106 @@ elif ! [[ -d $CPATH ]]; then
     mkdir -p "$CPATH"
 fi
 
-if [[ "$(pidof conky)" ]]; then
-    TEMPFILE=$(mktemp --tmpdir conky.XXXX)
-    while read -r line; do
-        echo "$line" >> "$TEMPFILE"
-    done <<< "$(pgrep -a conky)"
-fi
-
-for f in "${FILES[@]}"; do
-    NAME=$(basename "$f")
-    if [[ $NAME = *conkyrc ]] || [[ $NAME = *conky ]]; then
-        if [[ -e $TEMPFILE ]] && grep -q "$f" "$TEMPFILE"; then
-            LIST="$LIST TRUE $NAME"
-        else
-            LIST="$LIST FALSE $NAME"
-        fi
+running_conky() {
+    if [[ $(pidof conky) ]]; then
+        TEMPFILE=$(mktemp --tmpdir conky.XXXX)
+        pgrep -a conky > "$TEMPFILE"
     fi
-done
+}
 
-############################ Functions
+readonly FILES=($(find -L "$CPATH" -maxdepth 4 -type f))
+find_conky() {
+    LIST=""
+    for f in "${FILES[@]}"; do
+        NAME=$(basename "$f")
+        if [[ $NAME = *conkyrc ]] || [[ $NAME = *conky ]] || [[ $NAME == 'conkyrc' ]]; then
+            if [[ -e $TEMPFILE ]] && grep -q "$f" "$TEMPFILE"; then
+                LIST="$LIST TRUE $NAME"
+            else
+                LIST="$LIST FALSE $NAME"
+            fi
+        fi
+    done
+}
 
 write_Sessions() {
-    SFILE="$CPATH/$1"
-    echo "sessionfile= $SFILE"
-    if ! [[ -f $SESSIONS ]]; then echo -n > "$SESSIONS"; fi
-    if grep -qx "$SFILE" "$SESSIONS"; then
+    SESSIONFILE="$CPATH/$1"
+    echo "sessionfile= $SESSIONFILE"
+    [[ ! -f $SESSIONS ]] && echo -n "" > "$SESSIONS"
+    if grep -qx "$SESSIONFILE" "$SESSIONS"; then
         if [[ $2 = "-z" ]]; then
-            $QUESTION --title="Conky sessionfile" $ICON --width=250 --height=100 \
-                --text="<big>Filename already in use</big>\n\nOverwrite it?" &>/dev/null
-            if [[ $? == 1 ]]; then exit 0; fi
+            local XMSG="<big>Filename already in use</big>\n\nOverwrite it?"
+            if ! $QUESTION --title="Conky sessionfile" --text="$XMSG" &>/dev/null; then
+                exit 0
+            fi
         else
             echo "Session was previously saved with the same name. Overwrite it? (y|N)"
             read -r ans
-            if ! grep -q '[yY]' <<< "$ans"; then exit 0; fi
+            if ! grep -q '[yY]' <<< "$ans"; then
+                exit 0
+            fi
         fi
     else
         cp "$SESSIONS" "$SESSIONS.bkp"
-        echo "$SFILE" >> "$SESSIONS"
+        echo "$SESSIONFILE" >> "$SESSIONS"
     fi
 }
 
 choose_Conkys() {
-    while ! [[ "$ANSWER" ]]; do
-        ANSWER=$(zenity $ICON --list --title="$TITLE" --separator=" " \
-            --text="<big>Session will be saved to:</big>\n\n <b>$SFILE</b>\n" \
-            --checklist --width=450 --height=500 --multiple \
-            --column="Select" --column="Conky Name" $LIST)
+    while ! [[ $ANSWER ]]; do
+        running_conky
+        find_conky
+        ANSWER=$($CHECKLIST --title="$TITLE" --separator=" " --text="$MSG" --column="Select" --column="Conky" $LIST)
         if [[ $? == 1 ]]; then
-            if [[ -f $SESSIONS.bkp ]]; then mv "$SESSIONS.bkp" "$SESSIONS"; fi
-            ANSWER="None"
-        elif ! [[ "$ANSWER" ]]; then
-            $QUESTION --title="$TITLE" --width=250 --height=100 \
-                --text="<big>No Conky Selected</big>\n\nClose all running Conkys and exit?" \
-                --cancel-label="Go Back" &>/dev/null
-            if [[ $? = 1 ]]; then
-                if [[ -f $SESSIONS.bkp ]]; then mv $SESSIONS.bkp $SESSIONS; fi
-                unset ANSWER
+            [[ -f $SESSIONS.bkp ]] && mv "$SESSIONS.bkp" "$SESSIONS"
+            ANSWER=NONE
+        elif ! [[ $ANSWER ]]; then
+            if [[ $(pidof conky) ]]; then
+                local XMSG="<big>No Conky Selected</big>\n\nClose all running Conkys and exit?"
+                if $QUESTION --title="$TITLE" --cancel-label="Go Back" --text="$XMSG" &>/dev/null; then
+                    ANSWER=NONE ; killall conky
+                else
+                    [[ -f $SESSIONS.bkp ]] && mv "$SESSIONS.bkp" "$SESSIONS"
+                    ANSWER="" ; continue
+                fi
             else
-                if [[ "$(pidof conky)" ]]; then killall conky; fi
-                ANSWER="None"
+                ANSWER=NONE
             fi
         else
-            echo -n > "$SFILE"
-            if [[ $(pidof conky) ]]; then killall conky; fi
-            for n in $ANSWER; do
-                for f in "${FILES[@]}"; do
-                    if [[ $(basename "$f") = "$n" ]]; then
-                        echo -e "conky -c $f & sleep 0.5" >> "$SFILE"
-                        conky -c "$f"; sleep 0.1; break
+            echo -n "" > "$SESSIONFILE"
+            [[ $(pidof conky) ]] && killall conky
+            for name in $ANSWER; do
+                for file in "${FILES[@]}"; do
+                    if [[ $(basename "$file") = "$name" ]]; then
+                        echo "$file"
+                        echo "conky -c $file & sleep 0.5" >> "$SESSIONFILE"
+                        conky -c "$file" ; break
                     fi
                 done
             done
         fi
-        if [[ -e $TEMPFILE ]]; then rm -f "$TEMPFILE"; fi
+        [[ -e $TEMPFILE ]] && rm -f "$TEMPFILE"
     done
 }
 
-#########################  Check args and run gui
 
 case $1 in
-    -h|--help)
-        echo -e "$USAGE"
-        exit 0
-        ;;
+    -h|--help) echo -e "$USAGE" ; exit 0 ;;
     -f|--files)
         if [[ "$2" ]]; then
-            SFILE="$2"
-            write_Sessions "$SFILE"
+            SESSIONFILE="$2"
+            write_Sessions "$SESSIONFILE"
         else
-            echo -e "\n\tNo saved-session file specified!\n\n$USAGE1"; exit 2
+            echo "No saved-session file specified!" ; echo -e "$USAGE" ; exit 2
         fi
         ;;
     -z)
-        ENTRY=$(zenity $ICON --entry --width=350 --height=200 --title="Save Conky sessionfile" \
-            --entry-text="New Session Name" --text="File to be saved in\n\n$CPATH/\n")
+        XMSG="File to be saved in\n\n$CPATH/\n"
+        ENTRY=$($TEXTENTRY --title="Save Conky sessionfile" --entry-text="New Session Name" --text="$XMSG")
         if [[ $? == 1 ]]; then exit 0; fi
         if [[ -z $ENTRY ]]; then
-            zenity --info $ICON --title="Conky sessionfile" --width=200 --height=100 \
-                --text="No File Specified Exiting..." &>/dev/null && exit 1
+            XMSG="No File Specified Exiting..."
+            $INFO --title="Conky sessionfile" --text="$XMSG" &>/dev/null ; exit 1
         else
             write_Sessions "$ENTRY" "-z"
         fi
diff --git a/scripts/manjaro-editors-pipemenu b/scripts/manjaro-editors-pipemenu
--- a/scripts/manjaro-editors-pipemenu
+++ b/scripts/manjaro-editors-pipemenu
@@ -1,24 +1,21 @@
 #!/usr/bin/env bash
 
-
 # Manjaro Code Pipemenu
 # written by Nathaniel Maia, December 2017
 
 # Add something like this to your menu.xml
-# <menu execute="manjaro-code-pipemenu" id="code" label="Code"/>
+# <menu execute="al-code-pipemenu" id="code" label="Code"/>
 
 NAME="code"
 PNAME="Code"
 FAIL_MSG="No Apps Installed"
 
-# make sure these two arrays are the same amount of items
-# if not things will go wrong and you will have blank space
 CMD=(atom brackets emacs geany gedit gvim leafpad mousepad vscode subl3)
 DESC=(Atom Brackets Emacs Geany Gedit Gvim Leafpad Mousepad "Visual Studio" Sublime)
 
 # source lib file
-if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
+if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg"
     exit 1
 fi
 
@@ -31,14 +28,20 @@ menu_Body() {
 }
 
 menuStart "$NAME" "$PNAME"
-num=0
 for x in "${CMD[@]}"; do
-    if hash "$x" &>/dev/null; then num=$((num + 1)); fi
+    if hash "$x" &>/dev/null; then
+        num=1 ; break
+    fi
 done
 if [[ $num -gt 0 ]]; then
     menu_Body
 else
     menuSeparator "$FAIL_MSG"
+    if hash pamac-manager &>/dev/null; then
+        menuItem "Install with Package Manager" "pamac-manager"
+    elif hash termite pacli &>/dev/null; then
+        menuItem "Install with Package Manager" "termite -e pacli"
+    fi
 fi
 menuEnd
 
diff --git a/scripts/manjaro-files-pipemenu b/scripts/manjaro-files-pipemenu
--- a/scripts/manjaro-files-pipemenu
+++ b/scripts/manjaro-files-pipemenu
@@ -1,28 +1,24 @@
 #!/usr/bin/env bash
 
-
 # A File Managment Pipemenu for Manjaro
 # written by Nathaniel Maia, December 2017
 
 # Add something like this to your menu.xml
-# <menu execute="manjaro-filemngr-pipemenu" id="filemngr" label="File Management"/>
+# <menu execute="al-filemngr-pipemenu" id="filemngr" label="File Management"/>
 
 NAME="filemngr"
 PNAME="File Management"
 FAIL_MSG="No Apps Installed"
 
-# make sure these two arrays are the same amount of items
-# if not things will go wrong and you will have blank space
 CMD=(catfish thunar pcmanfm spacefm caja nautilus nemo dolphin
-     etcher file-roller xarchiver
+     file-roller xarchiver
      )
 DESC=(Catfish Thunar PCmanFM SpaceFM Caja Nautilus Nemo Dolphin
-      Etcher "File Roller" xArchiver
+      "File Roller" xArchiver
       )
 
-# source lib file
-if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
+if ! . "/usr/lib/manjaro/common/al-include.cfg" 2> /dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg"
     exit 1
 fi
 
@@ -35,14 +31,20 @@ menu_Body() {
 }
 
 menuStart "$NAME" "$PNAME"
-num=0
 for x in "${CMD[@]}"; do
-    if hash "$x" &>/dev/null; then num=$((num + 1)); fi
+    if hash "$x" &>/dev/null; then
+        num=1 ; break
+    fi
 done
 if [[ $num -gt 0 ]]; then
     menu_Body
 else
     menuSeparator "$FAIL_MSG"
+    if hash pamac-manager &>/dev/null; then
+        menuItem "Install with Package Manager" "pamac-manager"
+    elif hash termite pacli &>/dev/null; then
+        menuItem "Install with Package Manager" "termite -e pacli"
+    fi
 fi
 menuEnd
 
diff --git a/scripts/manjaro-graphics-pipemenu b/scripts/manjaro-graphics-pipemenu
--- a/scripts/manjaro-graphics-pipemenu
+++ b/scripts/manjaro-graphics-pipemenu
@@ -1,24 +1,24 @@
 #!/usr/bin/env bash
 
-
 # Manjaro Graphics Pipemenu
 # written by Nathaniel Maia, December 2017
 
 # Add something like this to your menu.xml
-# <menu execute="manjaro-graphics-pipemenu" id="graphics" label="Graphics"/>
+# <menu execute="al-graphics-pipemenu" id="graphics" label="Graphics"/>
 
 NAME="graphics"
 PNAME="Graphics"
 FAIL_MSG="No Apps Installed"
 
-# make sure these two arrays are the same amount of items
-# if not things will go wrong and you will have blank space
-CMD=(gimp inkscape kdenlive krita openshot pinta gpicview gpick)
-DESC=(Gimp Inkscape Kdenlive Krita Openshot Pinta "Picture Viewer" Gpick)
+CMD=(gimp inkscape obs-studio simplescreenrecorder kdenlive krita openshot pinta
+     viewnior gpicview gpick gcolor2 xfce4-screenshooter
+     )
+DESC=(Gimp Inkscape "OBS Studio" SimpleScreenRecorder Kdenlive Krita Openshot Pinta
+      Viewnior "Picture Viewer" Gpick Gcolor2 "Xfce Screenshooter"
+      )
 
-# source lib file
-if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
+if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg"
     exit 1
 fi
 
@@ -31,14 +31,20 @@ menu_Body() {
 }
 
 menuStart "$NAME" "$PNAME"
-num=0
 for x in "${CMD[@]}"; do
-    if hash "$x" &>/dev/null; then num=$((num + 1)); fi
+    if hash "$x" &>/dev/null; then
+        num=1 ; break
+    fi
 done
 if [[ $num -gt 0 ]]; then
     menu_Body
 else
     menuSeparator "$FAIL_MSG"
+    if hash pamac-manager &>/dev/null; then
+        menuItem "Install with Package Manager" "pamac-manager"
+    elif hash termite pacli &>/dev/null; then
+        menuItem "Install with Package Manager" "termite -e pacli"
+    fi
 fi
 menuEnd
 
diff --git a/scripts/manjaro-help-pipemenu b/scripts/manjaro-help-pipemenu
--- a/scripts/manjaro-help-pipemenu
+++ b/scripts/manjaro-help-pipemenu
@@ -1,54 +1,38 @@
 #!/usr/bin/env bash
 
-#    manjaro-help-pipemenu - an Openbox pipemenu for displaying help files
-#
-#    This program is free software: you can redistribute it and/or modify
-#    it under the terms of the GNU General Public License as published by
-#    the Free Software Foundation, either version 3 of the License, or
-#    (at your option) any later version.
-#
-#    This program is distributed in the hope that it will be useful,
-#    but WITHOUT ANY WARRANTY; without even the implied warranty of
-#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#    GNU General Public License for more details.
-#
-#    You should have received a copy of the GNU General Public License
-#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# al-help-pipemenu - an Openbox pipemenu for displaying help files
 
+readonly HELP='
+al-help-pipemenu an Openbox Pipe Menu for displaying help files
+It should normally be called from an openbox menu.
 
-HELP='    manjaro-help-pipemenu an Openbox Pipe Menu for displaying help files
-    It should normally be called from an openbox menu.
 Options (usually passed from the menu):
     -h --help   show this message
-    If manjaro-help-pipemenu is called with no options (the usual method),
-    it will output an xml openbox pipemenu displaying various help links,
+
+If al-help-pipemenu is called with no options (the usual method),
+it will output an xml openbox pipemenu displaying various help links,
 '
 for i in "$@"; do
     case "$i" in
-        -h|--help)
-            echo "$HELP"
-            exit 0
-            ;;
+        -h|--help) echo "$HELP" ; exit 0
     esac
 done
 
-MANJARO_COMMON_LIBDIR='/usr/lib/manjaro/common'
-
-if ! . "$MANJARO_COMMON_LIBDIR/manjaro-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source manjaro-include.cfg in $MANJARO_COMMON_LIBDIR" >&2
-    exit 1
+if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
+    echo $"Error: Failed to source /usr/lib/manjaro/common/al-include.cfg" >&2 ; exit 1
 fi
 
 menuStart
 menuSeparator 'ARCHLABS LINUX ONLINE'
-menuItem 'Manjaro Homepage' 'exo-open "https://manjaroblog.wordpress.com/"'
+menuItem 'Manjaro Homepage' 'exo-open "https://www.manjarolinux.com/"'
 menuItem 'Manjaro Reddit' 'exo-open "https://www.reddit.com/r/ManjaroLinux/"'
-menuItem 'Manjaro Forum' 'exo-open "https://www.tapatalk.com/groups/manjaro/index.php"'
+menuItem 'Manjaro Forum' 'exo-open "https://forum.manjarolinux.com/"'
 menuItem 'Manjaro Google+' 'exo-open "https://plus.google.com/u/0/communities/111177505820810068511"'
+menuItem 'Manjaro Knowledge Base' 'exo-open "https://manjaro-knowledge-base.gitbooks.io/knowledge_base/content/"'
 
 menuSeparator 'ARCHLABS LINUX HELP'
-menuItem 'Forum Basic Help & Support' 'exo-open "http://manjaro.prophpbb.com/forum7.html"'
-menuItem 'Scripts, Tutorials & Tips' 'exo-open "https://www.tapatalk.com/groups/manjaro/configs-scripts-tutorials-and-tips-f13/"'
+menuItem 'Forum Basic Help & Support' 'exo-open "https://forum.manjarolinux.com/c/newbie-corner"'
+menuItem 'Scripts, Tutorials & Tips' 'exo-open "https://forum.manjarolinux.com/c/configs-scripts-tutorials-tips"'
 
 menuSeparator 'GUIDES'
 
diff --git a/scripts/manjaro-kb-pipemenu b/scripts/manjaro-kb-pipemenu
--- a/scripts/manjaro-kb-pipemenu
+++ b/scripts/manjaro-kb-pipemenu
@@ -1,28 +1,15 @@
 #!/usr/bin/env bash
 
-# manjaro-kb-pipemenu - an Openbox pipemenu for displaying keybinds
-# Copyright (C) 2015 damo    <damo@bunsenlabs.org>
-#
-# This program is free software: you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation, either version 3 of the License, or
-# (at your option) any later version.
-#
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
-#
-# You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# al-kb-pipemenu - an Openbox pipemenu for displaying keybinds
+# Copyright (C) 2015 damo <damo@bunsenlabs.org>
+# Copyright (C) 2018 Nathaniel Maia  <natemaia10@gmail.com>
+# Renamed and rewritten for Manjaro and zenity
 
-# NB The keybinds in the menu are clickable, except for the Openbox
-# commands, which just exit the menu
-# manjaro-kb is used to parse rc.xml and send the output to a textfile
-
-#	Renamed and Rewritten for Manjaro and zenity
-
-HELP='\tmanjaro-kb-pipemenu an Openbox Pipe Menu for displaying keybinds
+readonly KBSCRIPT="al-kb"
+readonly CFG_DIR="$HOME/.config/openbox"
+readonly RCPATH="$CFG_DIR/rc.xml"
+readonly KBTEXT="$CFG_DIR/kbinds.txt"
+readonly HELP='\tal-kb-pipemenu an Openbox Pipe Menu for displaying keybinds
 \tIt should normally be called from an openbox menu.
 \nOptions (usually passed from the menu):
 \t-h --help   show this message
@@ -30,41 +17,33 @@ HELP='\tmanjaro-kb-pipemenu an Openbox Pipe Menu for displaying keybinds
 \t(The keybinds in the menu are clickable, except for the Openbox
 \tcommands, which just exit the menu.)
 \t--rcedit    backup and edit rc.xml
-\nIf manjaro-keyboard-pipemenu is called with no options (the usual method),
+\nIf al-keyboard-pipemenu is called with no options (the usual method),
 it will output an xml openbox pipemenu for displaying keybindings.
 \tNOTE: Some of the functionality of this pipemenu depends on the script
-/usr/bin/manjaro-kb which is provided by the package "manjaro-utilities"'
+/usr/bin/al-kb which is provided by the package "manjaro-utilities"'
+
 case "$@" in
-    -h|--help)
-        echo -e "$HELP"
-        exit 0
+    -h|--help) echo -e "$HELP" ; exit 0
 esac
 
-MANJARO_COMMON_LIBDIR="/usr/lib/manjaro/common"
-USR_CFG_DIR="$HOME/.config/openbox"
-KBSCRIPT="manjaro-kb"
-RCPATH="$USR_CFG_DIR/rc.xml"
-KBTEXT="$USR_CFG_DIR/kbinds.txt"
-
-if ! . "$MANJARO_COMMON_LIBDIR/manjaro-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to locate manjaro-include.cfg in $MANJARO_COMMON_LIBDIR" >&2
+if ! . "/usr/lib/manjaro/common/al-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to locate /usr/lib/manjaro/common//al-include.cfg" >&2
     exit 1
 fi
-# test if manjaro-kb exists in path
+
 if ! type "$KBSCRIPT" &>/dev/null; then
     menuStart
-    menuSeparator "$KBSCRIPT is not available. Try installing Manjaro-utilities."
+    menuSeparator "$KBSCRIPT is not available. Try installing manjaro-pipemenus."
     menuEnd
     exit 1
 fi
 
-if [[ $1 = '--rcedit' ]]; then # "Backup & Edit rc.xml" is chosen in menu
-    # backup rc.xml first
+if [[ $1 = '--rcedit' ]]; then
     NOW=$(date +"%Y%m%d-%H%M")
     RCBKP="$RCPATH.$NOW"
     cp "$RCPATH" "$RCBKP"
     if hash exo-open &>/dev/null; then
-        exo-open "$RCPATH"        # open rc.xml in default editor
+        exo-open "$RCPATH"
     else
         termite -e "$EDITOR $RCPATH"
     fi
@@ -72,11 +51,10 @@ if [[ $1 = '--rcedit' ]]; then # "Backup & Edit rc.xml" is chosen in menu
 fi
 
 if [[ $1 = '--keybinds' ]]; then
-    # run script to write kbinds.txt, suppress terminal output
     "$KBSCRIPT" > /dev/null
     menuStart
     menuSeparator "Openbox window commands"
-    while read -r a b c; do      # write out Openbox commands (not clickable)
+    while read -r a b c; do
         if [[ "$a" = "o" ]]; then
             curItem=$(printf "%-20s %s" "$b" "$c")
             menuItem "$curItem" "echo >/dev/null 2>&1"
@@ -85,7 +63,7 @@ if [[ $1 = '--keybinds' ]]; then
 
     menuSeparator
     menuSeparator "Run commands"
-    while read -r a b c; do      # write out 'Run' commands (clickable)
+    while read -r a b c; do
         if [[ "$a" = "x" ]]; then
             curItem=$(printf "%-20s %s" "$b" "$c")
             menuItem "$curItem" "$c"
@@ -95,12 +73,11 @@ if [[ $1 = '--keybinds' ]]; then
     exit 0
 fi
 
-# pipemenu
 menuStart
-    menuItem "Backup and Edit rc.xml" "manjaro-kb-pipemenu --rcedit"
+    menuItem "Backup and Edit rc.xml" "al-kb-pipemenu --rcedit"
     menuSeparator
-    menuItem "Display Keybinds in window" "manjaro-kb --gui"
-    echo '        <menu execute="manjaro-kb-pipemenu --keybinds" id="Display keybinds" label="Display Keybinds in menu"/>'
+    menuItem "Display Keybinds in window" "al-kb --gui"
+    echo '        <menu execute="al-kb-pipemenu --keybinds" id="Display keybinds" label="Display Keybinds in menu"/>'
 menuEnd
 
 exit 0
diff --git a/scripts/manjaro-mail-pipemenu b/scripts/manjaro-mail-pipemenu
--- a/scripts/manjaro-mail-pipemenu
+++ b/scripts/manjaro-mail-pipemenu
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 
-
 # A pipemenu base script/template for creating category based pipemenus
 # written by Nathaniel Maia, December 2017 for Manjaro
 
@@ -11,14 +10,11 @@ NAME="mail"
 PNAME="Mail"
 FAIL_MSG="No Apps Installed"
 
-# make sure these two arrays are the same amount of items
-# if not things will go wrong and you will have blank space
 CMD=(evolution geary thunderbird mailspring)
 DESC=(Evolution Geary Thunderbird Mailspring)
 
-# source lib file
-if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
+if ! . "/usr/lib/manjaro/common/al-include.cfg" 2> /dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg"
     exit 1
 fi
 
@@ -31,14 +27,20 @@ menu_Body() {
 }
 
 menuStart "$NAME" "$PNAME"
-num=0
 for x in "${CMD[@]}"; do
-    if hash "$x" &>/dev/null; then num=$((num + 1)); fi
+    if hash "$x" &>/dev/null; then
+        num=1 ; break
+    fi
 done
 if [[ $num -gt 0 ]]; then
     menu_Body
 else
     menuSeparator "$FAIL_MSG"
+    if hash pamac-manager &>/dev/null; then
+        menuItem "Install with Package Manager" "pamac-manager"
+    elif hash termite pacli &>/dev/null; then
+        menuItem "Install with Package Manager" "termite -e pacli"
+    fi
 fi
 menuEnd
 
diff --git a/scripts/manjaro-media-pipemenu b/scripts/manjaro-media-pipemenu
--- a/scripts/manjaro-media-pipemenu
+++ b/scripts/manjaro-media-pipemenu
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 
-
 # A pipemenu base script/template for creating category based pipemenus
 # written by Nathaniel Maia, December 2017 for Manjaro
 
@@ -11,34 +10,45 @@ NAME="media"
 PNAME="Media"
 FAIL_MSG="No Apps Installed"
 
-# make sure these two arrays are the same amount of items
-# if not things will go wrong and you will have blank space
-CMD=(audacious clementine guvcview lollypop rhythmbox spotify vlc mpv gnome-mpv sonata cantata)
-DESC=(Audacious "Clementine Music Player" guvcview Lollypop Rhythmbox Spotify VLC MPV Gnome-MPV Sonata Cantata)
+CMD=(audacity audacious deadbeef clementine guvcview lollypop
+     gnome-music rhythmbox spotify vlc mpv gnome-mpv sonata cantata
+     kodi)
+DESC=(Audacity Audacious DeaDBeeF Clementine guvcview Lollypop
+      "Gnome Music" Rhythmbox Spotify VLC MPV Gnome-MPV Sonata Cantata
+      Kodi)
 
-# source lib file
-if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
+if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg"
     exit 1
 fi
 
 menu_Body() {
     for ((i=0; i<${#CMD[@]}; i++)); do
         if hash "${CMD[$i]}" &>/dev/null; then
-            menuItem "${DESC[$i]}" "${CMD[$i]}"
+            if [[ "${CMD[$i]}" == 'mpv' ]]; then
+                menuItem "${DESC[$i]}" "${CMD[$i]} --player-operation-mode=pseudo-gui"
+            else
+                menuItem "${DESC[$i]}" "${CMD[$i]}"
+            fi
         fi
     done
 }
 
 menuStart "$NAME" "$PNAME"
-num=0
 for x in "${CMD[@]}"; do
-    if hash "$x" &>/dev/null; then num=$((num + 1)); fi
+    if hash "$x" &>/dev/null; then
+        num=1 ; break
+    fi
 done
 if [[ $num -gt 0 ]]; then
     menu_Body
 else
     menuSeparator "$FAIL_MSG"
+    if hash pamac-manager &>/dev/null; then
+        menuItem "Install with Package Manager" "pamac-manager"
+    elif hash termite pacli &>/dev/null; then
+        menuItem "Install with Package Manager" "termite -e pacli"
+    fi
 fi
 menuEnd
 
diff --git a/scripts/manjaro-places-pipemenu b/scripts/manjaro-places-pipemenu
--- a/scripts/manjaro-places-pipemenu
+++ b/scripts/manjaro-places-pipemenu
@@ -1,234 +1,155 @@
-#!/bin/sh
-#    bl-places-pipemenu - an openbox places pipe menu
-#    Copyright (C) 2010~2016  John Crawley <john@bunsenlabs.org>
-#
-#    This program is free software: you can redistribute it and/or modify
-#    it under the terms of the GNU General Public License as published by
-#    the Free Software Foundation, either version 3 of the License, or
-#    (at your option) any later version.
-#
-#    This program is distributed in the hope that it will be useful,
-#    but WITHOUT ANY WARRANTY; without even the implied warranty of
-#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#    GNU General Public License for more details.
+#!/usr/bin/env bash
 
-#    NB The default shell (usually dash, not bash) is invoked
-#    because it is faster.
+# al-places-pipemenu - an openbox places pipe menu
+# Copyright (C) 2010~2016  John Crawley <john@bunsenlabs.org>
+# Copyright (C) 2017~2018  Nathaniel Maia <natemaia10@gmail.com>
 
-# Usage: add
-# <menu id="places" label="Places" execute="/path/to/manjaro-places-pipemenu ~/" />
-# to your .config/openbox/menu.xml
-
+# <menu id="places" label="Places" execute="/path/to/al-places-pipemenu ~/" />
 # or, if you want the "recent files" menu incorporated at the top, use:
-# <menu id="places" label="Places" execute="/path/to/manjaro-places-pipemenu --recent ~/" />
-# make sure you have manjaro-recent-files-pipemenu somewhere, and enter its path below.
+# <menu id="places" label="Places" execute="/path/to/al-places-pipemenu --recent ~/" />
+# make sure you have al-recent-files-pipemenu, and enter its path below.
 
-# path to your "recent files" script, if you want to incorporate it:
-recent_script=/usr/bin/manjaro-recent-files-pipemenu
-# Command to open folders at "Browse here..." - any file manager
-open_folder_cmd=thunar
-# Default command to open files with - others might be exo-open, gnome-open, thunar, pcmanfm...
-default_open_cmd=exo-open
-# Text editor of choice
-text_editor=geany
+readonly terminal=termite
+readonly text_editor=geany
+readonly open_folder_cmd=thunar
+readonly default_open_cmd=exo-open
+readonly recent_script=/usr/bin/al-recent-files-pipemenu
 
-# function to open files with default open command, or alternative command for certain files
-# - add other conditions to choice
 open_file() {
-    if hash exo-open &>/dev/null; then
+    if hash "$default_open_cmd" &>/dev/null; then
         exec "$default_open_cmd" "$1"
     elif hash $text_editor &>/dev/null; then
         exec "$text_editor" "$1"
+    elif hash $terminal &>/dev/null; then
+        ($terminal -e "$EDITOR $1") &>/dev/null &
     else
-        exec "$termite -e" "$EDITOR $1"
+        echo "$0 : failed to open $2" ; exit 1
     fi
-
-    # [ -x "$1" ] && exec "$text_editor" "$1"               # comment out this line if you don't want to edit executables instead of executing
-    # #[ -x "$1" ] && exec "x-terminmanjaro-emulator -e" "$1"    # uncomment this and comment out previous line to run executables in terminal instead of editing
-    # [ "${1##*.}" = desktop ] && exec "$text_editor" "$1"  # comment out this line if you don't want to edit .desktop files instead of executing
-    # exec "$default_open_cmd" "$1"                         # use default open command if above conditions not satisfied
 }
 
-# extra dotfiles and directories to display in HOME folder (dotfiles are hidden by default)
-# edit the list (space separated, surrounded by single quotes) or comment this line out, to taste:
-shown_dotfiles='.config .local .Xresources .Xdefaults .bash_aliases .gorice .themes .bashrc .zshrc .xinitrc .gtkrc-2.0.mine .xprofile .xsessionrc .xsession-errors'
+readonly shown_dotfiles=".config .local .vim .vimrc .Xresources .Xmodmap .bashrc .zshrc .xinitrc .gtkrc-2.0.mine .xprofile .xsessionrc"
+readonly HELP='
+al-places-pipemenu an Openbox Pipe Menu for showing a directory tree
+It should normally be called from an openbox menu.
 
-# By default, this script will display directories separately, before files.
-# To change this behaviour, see NOTE1, NOTE2 and NOTE3 below, near end of page.
-
-HELP='    manjaro-places-pipemenu an Openbox Pipe Menu for showing a directory tree
-    It should normally be called from an openbox menu.
 Usage:
-manjaro-places-pipemenu [options] [directory tree root]
+    al-places-pipemenu [options] [directory tree root]
 
 Options:
-    -h --help           show this message
-    --open  <filepath>  open a file with configured default application
-    (in this case the script will not output a menu)
+    -h,--help           show this message
     --recent            incorporate a "recent files" submenu
+    --open <filepath>   open a file with configured default application
+                        (in this case the script will not output a menu)
 
-If a directory tree root is not specified, $HOME will be used.
+    If a directory tree root is not specified, $HOME will be used.
 
 Configuration:
-/usr/bin/manjaro-places-pipemenu may be edited directly for system-wide changes,
-or copied to ~/bin and edited there for per-user changes.
+    /usr/bin/al-places-pipemenu may be edited directly for system-wide changes,
+    or copied to ~/bin and edited there for per-user changes.
 
 Editable variables and functions, at the top of the file:
-recent_script       path to a script outputting an openbox pipemenu
-open_folder_cmd     command to open folders - any file manager
-default_open_cmd    default command to open files
-text_editor         command to open text files
-open_file()         open files, using commands above, or alternatives
-shown_dotfiles      list of dotfiles to display (they are hidden by default)
+    recent_script       path to a script outputting an openbox pipemenu
+    open_folder_cmd     command to open folders - any file manager
+    default_open_cmd    default command to open files
+    text_editor         command to open text files
+    open_file()         open files, using commands above, or alternatives
+    shown_dotfiles      list of dotfiles to display (they are hidden by default)
 
-By default, this script will display directories separately, before files.
-To change this behaviour, see NOTE1, NOTE2 and NOTE3 near end of file.
+    By default, this script will display directories separately, before files.
+    To change this behaviour, see NOTE1, NOTE2 and NOTE3 near end of file.
 '
 
-############################################################################
 
 case $1 in
--h|--help)
-    echo "$HELP"
-    exit 0
-    ;;
-# if "--open" option is sent as $1, open file ($2) instead of generating menu
---open)
-    open_file "$2"
-    echo "$0 : failed to open $2" >&2
-    exit # in case exec command fails
-    ;;
-# if "--recent" option is sent, incorporate "recent files" menu
---recent)
-    shift
-    output='<openbox_pipe_menu>
-'
-    if [ -x "$recent_script" ]
-    then
-        output="${output}<separator label=\"Recently opened...\" />
-<menu execute=\"$recent_script\" id=\"recent\" label=\"files\" />
-"
-    else
-        echo "$0 : cannot find executable script $recent_script" >&2
-    fi
-    ;;
-*)
-    output='<openbox_pipe_menu>
-'
-    ;;
+    -h|--help) echo "$HELP" ; exit 0 ;;
+    --open) open_file "$2" ;;
+    --recent)
+        shift
+        output='<openbox_pipe_menu>'
+        if [[ -x $recent_script ]]; then
+            output="$output
+  <separator label=\"Recently opened...\"/>
+  <menu execute=\"$recent_script\" id=\"recent\" label=\"files\"/>"
+        else
+            echo "$0 : cannot find executable script $recent_script" >&2
+        fi
+        ;;
+    *) output='<openbox_pipe_menu>'
 esac
 
-path="${1:-$HOME}"  # default starting place is ~, otherwise $1
-path="${path%/}"
-[ -d "$path" ] || { echo "$0 : $path is not a directory" >&2; exit 1; }
+path=${1:-$HOME}
+path=${path%/}
 
-case "$path" in    # only escape if string needs it
-*\&*|*\<*|*\>*|*\"*|*\'*)
-    pathe=$(sed "s/\&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g;s/\"/\&quot;/g;s/'/\&apos;/g;" <<XXX
-$path
-XXX
-)
-    ;;
-*)
-    pathe=$path
-    ;;
+[[ -d $path ]] || { echo "$0 : $path is not a directory" >&2 ; exit 1 ; }
+
+# only escape if string needs it
+case $path in
+    *\&*|*\<*|*\>*|*\"*|*\'*) pathe=$(sed "s/\&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g;s/\"/\&quot;/g;s/'/\&apos;/g;" <<<"$path") ;;
+    *)                        pathe=$path
+esac
+case $pathe in
+    *\&apos\;*) pathe_apos=$(sed 's/\&apos;/\&apos;\&quot;\&apos;\&quot;\&apos;/g;' <<<"$pathe") ;;
+    *)          pathe_apos=$pathe
 esac
 
-case "$pathe" in
-*\&apos\;*)
-    pathe_apos=$(sed 's/\&apos;/\&apos;\&quot;\&apos;\&quot;\&apos;/g;'<<XXX
-$pathe
-XXX
-)
-    ;;
-*)
-    pathe_apos=$pathe
-    ;;
-esac
-
-output="$output<separator label=\"$pathe\" />
-<item label=\"Browse here...\">
+output="$output
+  <separator label=\"$pathe\"/>
+  <item label=\"Browse here...\">
     <action name=\"Execute\">
-        <command>
-         &apos;$open_folder_cmd&apos; &apos;$pathe_apos&apos;
-        </command>
+      <command>&apos;$open_folder_cmd&apos; &apos;$pathe_apos&apos;</command>
     </action>
-</item>
-<separator />
-"
+  </item>
+  <separator/>"
 
-unset extra_entries directories_menu files_menu
-[ "$path" = "$HOME" ] && extra_entries="$shown_dotfiles"
-for i in "$path"/* $extra_entries
-do
-    [ -e "$i" ] || continue    # only output code if file exists
-    shortname="${i##*/}"
+[[ "$path" == "$HOME" ]] && extra_entries="$shown_dotfiles"
+
+for i in $path/* $extra_entries; do
+
+    [[ ! -e $i ]] && continue
+    shortname=${i##*/}
+
     case $shortname in
-    *\&*|*\<*|*\>*|*\"*|*\'*)
-        shortnamee=$(sed "s/\&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g;s/\"/\&quot;/g;s/'/\&apos;/g;" <<XXX
-$shortname
-XXX
-)
-        ;;
-    *)
-        shortnamee=$shortname
-        ;;
+        *\&*|*\<*|*\>*|*\"*|*\'*) shortnamee=$(sed "s/\&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g;s/\"/\&quot;/g;s/'/\&apos;/g;" <<<"$shortname") ;;
+        *)                        shortnamee=$shortname
     esac
     case $shortnamee in
-    *\&apos\;*)
-        shortnamee_apos=$(sed 's/\&apos;/\&apos;\&quot;\&apos;\&quot;\&apos;/g;'<<XXX
-$shortnamee
-XXX
-)
-        ;;
-    *)
-        shortnamee_apos=$shortnamee
-        ;;
+        *\&apos\;*) shortnamee_apos=$(sed 's/\&apos;/\&apos;\&quot;\&apos;\&quot;\&apos;/g;' <<<"$shortnamee") ;;
+        *)          shortnamee_apos=$shortnamee
     esac
     case $shortnamee in
-    *_*)
-        shortnamee_label=$(sed 's/_/__/g;'<<XXX
-$shortnamee
-XXX
-)
-        ;;
-    *)
-        shortnamee_label=$shortnamee
-        ;;
+        *_*) shortnamee_label=$(sed 's/_/__/g;' <<<"$shortnamee") ;;
+        *)   shortnamee_label=$shortnamee
     esac
-    if [ -d "$i" ]
-    then
-# NOTE1 If you want directories and files listed together
-# change next line [directories_menu="$directories_menu] to read: [files_menu="$files_menu] (there is no final quote)
+
+    # NOTE1: If you want directories and files listed together
+    # change directories_menu="$directories_menu to: files_menu="$files_menu
+    if [[ -d $i ]]; then
         directories_menu="$directories_menu
-<menu id=\"${pathe_apos}/${shortnamee_apos}\" label=\"$shortnamee_label\" execute=\"&apos;$0&apos; &apos;${pathe_apos}/${shortnamee_apos}&apos;\" />"
+  <menu id=\"$pathe_apos/$shortnamee_apos\" label=\"$shortnamee_label\" execute=\"&apos;$0&apos; &apos;$pathe_apos/$shortnamee_apos&apos;\"/>"
     else
         files_menu="$files_menu
-<item label=\"$shortnamee_label\">
+  <item label=\"$shortnamee_label\">
     <action name=\"Execute\">
-        <command>
-        &apos;$0&apos; --open &apos;${pathe_apos}/${shortnamee_apos}&apos;
-        </command>
+      <command>&apos;$0&apos; --open &apos;${pathe_apos}/${shortnamee_apos}&apos;</command>
     </action>
-</item>"
+  </item>"
     fi
 done
 
-[ -n "$directories_menu" ] && {
-# NOTE2 comment out next 2 lines if you don't want "Directories" label
-#   output="${output}<separator label=\"Directories\" />
-#"
-    output="${output}${directories_menu}
+# NOTE2: uncomment these 2 lines if you want "Directories" label
+# output="$output
+# <separator label=\"Directories\"/>"
+[ -n "$directories_menu" ] && { output="${output}${directories_menu}"; }
+
+# NOTE3: uncomment these 2 lines if you want "Files" label
+# output="$output
+# <separator label=\"Files\"/>"
+[ -n "$files_menu" ] && { output="${output}${files_menu}"; }
+
+output="${output}
+</openbox_pipe_menu>
 "
-}
-[ -n "$files_menu" ] && {
-# NOTE3 comment out next 2 lines if you don't want "Files" label
-#   output="${output}<separator label=\"Files\" />
-#"
-    output="${output}${files_menu}
-"
-}
-output="${output}</openbox_pipe_menu>
-"
+
 printf '%s' "$output"
-exit
+
+exit 0
diff --git a/scripts/manjaro-polybar-pipemenu b/scripts/manjaro-polybar-pipemenu
--- a/scripts/manjaro-polybar-pipemenu
+++ b/scripts/manjaro-polybar-pipemenu
@@ -1,26 +1,15 @@
 #!/usr/bin/env bash
 
-#    manjaro-polybar-pipemenu - an Openbox pipemenu for polybar manipulation
-#    Written for Manjaro by Nathaniel Maia <natemaaia10@gmail.com> 2017
-#
-#    This program is free software: you can redistribute it and/or modify
-#    it under the terms of the GNU General Public License as published by
-#    the Free Software Foundation, either version 3 of the License, or
-#    (at your option) any later version.
-#
-#    This program is distributed in the hope that it will be useful,
-#    but WITHOUT ANY WARRANTY; without even the implied warranty of
-#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#    GNU General Public License for more details.
-#
-#    You should have received a copy of the GNU General Public License
-#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# al-polybar-pipemenu - an Openbox pipemenu for polybar manipulation
+# Written for Manjaro by Nathaniel Maia <natemaaia10@gmail.com> 2017
 
-HELP='\tmanjaro-polybar-pipemenu an Openbox Pipe Menu for Polybar
+readonly CPATH="$HOME/.config/polybar"
+readonly HELP='
+\tal-polybar-pipemenu an Openbox Pipe Menu for Polybar
 \tIt should normally be called from an openbox menu.
 \nOptions:
 \t-h --help   show this message
-\n\tIf manjaro-polybar-pipemenu is called with no options (the usual method),
+\n\tIf al-polybar-pipemenu is called with no options (the usual method),
 \tit will output an xml openbox pipemenu for handling polybar sessions,
 \tand editing configuration files.
 \nFor more information, see "man polybar"
@@ -30,12 +19,9 @@ case "$@" in
     -h|--help) echo -e "$HELP" ; exit 0
 esac
 
-MANJARO_COMMON_LIBDIR='/usr/lib/manjaro/common'
-CPATH="$HOME/.config/polybar"
 CONFIG="$CPATH/config"
-if ! . "$MANJARO_COMMON_LIBDIR/manjaro-include.cfg" 2>/dev/null; then
-    echo $"Error: Failed to source manjaro-include.cfg in $MANJARO_COMMON_LIBDIR"
-    exit 1
+if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
+    echo $"Error: Failed to source /usr/lib/manjaro/common/al-include.cfg" ; exit 1
 fi
 
 Editmenu() {
@@ -45,14 +31,16 @@ Editmenu() {
         while read -r pid cmd; do
             if [[ ${cmd%% *} = polybar ]]; then
                 CONF=${cmd##* }
-                CONFIG=${HOME}/.config/polybar/config
-                if [[ $CONF = polybar ]]; then
-                    CONF="$CONFIG"
-                fi
+                CONFIG=$HOME/.config/polybar/config
+                [[ $CONF = polybar ]] && CONF=$CONFIG
                 if hash exo-open &>/dev/null; then
                     menuItem "$CONF" "exo-open $CONFIG"
-                else
+                elif hash termite &>/dev/null; then
                     menuItem "$CONF" "termite -e '$EDITOR $CONFIG'"
+                elif hash st &>/dev/null; then
+                    menuItem "$CONF" "st -e $EDITOR $CONFIG"
+                elif hash urxvt &>/dev/null; then
+                    menuItem "$CONF" "urxvt -e '$EDITOR $CONFIG'"
                 fi
             fi
         done <<< "$(pgrep -a polybar)"
@@ -62,23 +50,23 @@ Editmenu() {
 
 Configs() {
     menuSubmenu "EditConfigs" "Edit Configs"
-    if type manjaro-polybar-edit &>/dev/null; then
-        menuItem "Edit Configs" "manjaro-polybar-edit"
+    if hash al-polybar-edit &>/dev/null; then
+        menuItem "Edit Configs" "al-polybar-edit"
     fi
     Editmenu
     menuSubmenuEnd
 }
 
 Launchmenu() {
-    if type manjaro-polybar-session &>/dev/null && [[ -f "$HOME/.config/polybar/sessions/openbox-sessionfile" ]]; then
+    if hash al-polybar-session &>/dev/null && [[ -f "$CPATH/sessions/openbox-sessionfile" ]]; then
         if [[ $(pidof polybar) ]]; then
-            menuItem "Restart Polybar" "manjaro-polybar-session"
+            menuItem "Restart Polybar" "al-polybar-session"
         else
-            menuItem "Start Polybar" "manjaro-polybar-session"
+            menuItem "Start Polybar" "al-polybar-session"
         fi
     fi
-    if type manjaro-polyzen &>/dev/null; then
-        menuItem "Polybar GUI" "manjaro-polyzen"
+    if type al-polyzen &>/dev/null; then
+        menuItem "Polybar GUI" "al-polyzen"
     fi
 }
 
diff --git a/scripts/manjaro-polybar-session b/scripts/manjaro-polybar-session
--- a/scripts/manjaro-polybar-session
+++ b/scripts/manjaro-polybar-session
@@ -1,82 +1,69 @@
 #!/usr/bin/env bash
 
-
-# manjaro-polybar-session: Polybar session launcher script for Manjaro
-# Specify a different sessionfile with [--session] or [-z] and passing a valid path
-# You can call this script regardless of WM and it will handle launching the right bars
-# simply add 'sleep 1; manjaro-polybar-session &' to your autostart
-
+# al-polybar-session: Polybar session launcher script for Manjaro
 # Copyright (C) 2017 Nathaniel Maia <natemaia10@gmail.com>
-# This program is provided free of charge and without warranty
-# I ask that if you use this program and make additions/changes
-# that you share and contribute back additions/changes
-
-####################################################################################
 
 if ! hash polybar read &>/dev/null; then
-    echo "[ERROR]: Missing Commands. It is required to install 'polybar' 'readline'"
-    exit 1
+    echo "[ERROR]: Missing Commands. It is required to install 'polybar' 'readline'" ; exit 1
 fi
 
-window_Managers=(bspwm i3 openbox xfce awesome)
-for i in "${window_Managers[@]}"; do
-    if [[ "$(wmctrl -m | grep -i name | awk '{print tolower($2)}')" == "$i" ]]; then
-        WM=$i && break
-    elif [[ "$(xprop -root -notype | grep "WM_NAME =" | tr -d '"' | awk '{print tolower($3)}')" == "$i" ]]; then
-        WM=$i && break
-    elif [[ "$(awk '{print tolower($0)}' <<< "$XDG_CURRENT_DESKTOP")" == "$i" ]]; then
-        WM=$i && break
-    fi
-done
+if ! [[ $WM ]]; then
+    readonly window_Managers=(bspwm i3 openbox xfce awesome)
+    for i in "${window_Managers[@]}"; do
+        if [[ $(wmctrl -m | grep -i name | awk '{print tolower($2)}') == "$i" ]]; then
+            readonly WM=$i ; break
+        elif [[ $(xprop -root -notype | grep "WM_NAME =" | tr -d '"' | awk '{print tolower($3)}') == "$i" ]]; then
+            readonly WM=$i ; break
+        elif [[ $(awk '{print tolower($0)}' <<< "$XDG_CURRENT_DESKTOP") == "$i" ]]; then
+            readonly WM=$i ; break
+        fi
+    done
+fi
 
-CONFPATH="$HOME/.config/polybar"
+readonly CONFPATH="$HOME/.config/polybar"
 if [[ "$WM" ]]; then
     SESSIONFILE="$CONFPATH/sessions/$WM-sessionfile"
 else
     SESSIONFILE="$CONFPATH/sessions/sessionfile"
 fi
 
-HELP="\nUSAGE:\n\tstart-polybar [OPTIONS] [SESSIONFILE]
+readonly HELP='\nUSAGE:\n\tal-polybar-session [OPTIONS] [SESSIONFILE]
 \nOPTIONS:
 \t-h, --help\tPrint this usage message and exit
-\t-z, --session\tUse passed sessionfile instead of default\n\t\t\t$SESSIONFILE
-\nEXAMPLES:\n\n\tRun the default session\n\t'manjaro-polybar-session'
-\n\tLoad a session saved in ~/.sessionfile\n\t'manjaro-polybar-session -z \$HOME/.sessionfile'
+\t-z, --session\tUse passed sessionfile instead of default
+\nEXAMPLES:\n\n\tRun the default session\n\t"al-polybar-session &"
+\n\tLoad a session saved in ~/.sessionfile\n\t"al-polybar-session -z $HOME/.sessionfile"
 \n\nSessions are handled on a per WM basis, for each WM, a WM-sessionfile will be created
-The script will launch the right session for the WM a sessionfile is specified
-Bars in a session can be chosen by running 'manjaro-polyzen' or manually configure
-\n\t$SESSIONFILE
+The script will launch the right session for each WM
+Bars in a session can be chosen by running "al-polyzen" or manually configure sessionfile
 \n\nTo have session run at startup add the following line to your autostart:
-\n\tsleep1; manjaro-polybar-session &"
+\n\tsleep1; al-polybar-session &'
 
 start_Session() {
-    if [ -f "$SESSIONFILE" ]; then
-        while [[ $(pidof polybar) ]]; do pkill polybar && sleep 0.2; done
+    if [[ -f $SESSIONFILE ]]; then
+        [[ $(pidof polybar) ]] && pkill polybar
         while read -r c b; do
-            if [[ "$c $b" =~ ^#.*$ ]] || [[ "$c $b" == "" ]]; then
+            if [[ "$c $b" =~ ^#.*$ ]] || ! ([[ $c ]] && [[ $b ]]) || ! [[ -f "$c" ]]; then
                 continue
-            fi
-            if [[ -e "$c" ]]; then
+            else
                 polybar --reload --config="$c" "$b" &
             fi
         done < "$SESSIONFILE"
     else
         echo -e "No sessionfile found
-        \n\tPlease setup your config directory then run 'manjaro-polyzen' to setup a sessionfile in\n\n\t'$CONFPATH'"
+        \n\tPlease setup your config directory then run 'al-polyzen' to setup a sessionfile in\n\n\t'$CONFPATH'"
     fi
-    sleep 1.5
-    if ! [[ "$(pidof polybar)" ]] && hash manjaro-polyzen &>/dev/null; then
-        manjaro-polyzen &
+    sleep 0.5
+    if ! [[ $(pidof polybar) ]] && hash al-polyzen &>/dev/null; then
+        al-polyzen &
     fi
 }
 
 case $1 in
-    *help|-h)
-        echo -e "$HELP" && exit 0
-        ;;
+    *help|-h) echo -e "$HELP" ; exit 0 ;;
     -z|*session)
         for arg in "$@"; do
-            if [ -f "$arg" ]; then
+            if [[ -f $arg ]]; then
                 SESSIONFILE="$arg"
             fi
         done
diff --git a/scripts/manjaro-polyzen b/scripts/manjaro-polyzen
--- a/scripts/manjaro-polyzen
+++ b/scripts/manjaro-polyzen
@@ -1,143 +1,160 @@
 #!/usr/bin/env bash
 
-
-# manjaro-polyzen: polybar session manager script for Manjaro
-
-# unless an alternate sessionfile is specified use WM-sessionfile
-# create a gui dialog with available bars found in config path
-# checkmarked bars will be added to sessionfile and started
-# starting bars is handled by either my seperate start-polybar script
-# or by polybar itself as a fallback if start-polybar script not found
-
+# al-polyzen: polybar session manager script for Manjaro
 # Copyright (C) 2017 Nathaniel Maia <natemaia10@gmail.com>
-# This program is provided free of charge and without warranty
-# I ask that if you use this program and make additions/changes
-# that you share and contribute back additions/changes
-
-#######################################################################
 
 if ! hash polybar zenity find read &>/dev/null; then
     echo "[ERROR]: Missing Commands. It is required to install 'polybar' 'zenity' 'readline' 'findutils'"
     exit 1
 fi
 
-window_Managers=(bspwm i3 openbox awesome xfce)
-for i in "${window_Managers[@]}"; do
-    if [[ "$(wmctrl -m | grep -i name | awk '{print tolower($2)}')" == "$i" ]]; then
-        WM=$i && break
-    elif [[ "$(xprop -root -notype | grep "WM_NAME =" | tr -d '"' | awk '{print tolower($3)}')" == "$i" ]]; then
-        WM=$i && break
-    elif [[ "$(awk '{print tolower($0)}' <<< "$XDG_CURRENT_DESKTOP")" == "$i" ]]; then
-        WM=$i && break
-    fi
-done
+if ! [[ $WM ]]; then
+    readonly window_Managers=(bspwm i3 openbox xfce awesome)
+    for i in "${window_Managers[@]}"; do
+        if [[ $(wmctrl -m | grep -i name | awk '{print tolower($2)}') == "$i" ]]; then
+            readonly WM=$i ; break
+        elif [[ $(xprop -root -notype | grep "WM_NAME =" | tr -d '"' | awk '{print tolower($3)}') == "$i" ]]; then
+            readonly WM=$i ; break
+        elif [[ $(awk '{print tolower($0)}' <<< "$XDG_CURRENT_DESKTOP") == "$i" ]]; then
+            readonly WM=$i ; break
+        fi
+    done
+fi
 
-CONFPATH="$HOME/.config/polybar"
+readonly TITLE="Manjaro Polybar Manager"
+readonly ICON="--window-icon=/usr/share/icons/Manjaro-Light/64x64/places/distributor-logo-archlabs.png"
+readonly CHECKLIST="zenity --width=400 --height=500 $ICON --list --checklist --multiple"
+readonly QUESTION="zenity --question $ICON --width=300"
+readonly CONFPATH="$HOME/.config/polybar"
+readonly START="$HOME/.config/openbox/autostart"
+readonly USAGE='
+USAGE: al-polyzen [OPTIONS] [SESSIONFILE]
+\nOPTIONS:
+\t-z, --session\tUse entered SESSIONFILE rather than default
+\t-h, --help\tPrint this usage message and exit
+\nWith no command options, the script uses the current WM-sessionfile
+To start session at login, add the following line to autostart:
+\tsleep 1; al-polybar-session &'
+
+# SESSIONFILE is mutable by user
 if [[ $WM ]]; then
     SESSIONFILE="$CONFPATH/sessions/$WM-sessionfile"
 else
     SESSIONFILE="$CONFPATH/sessions/sessionfile"
 fi
-
-USAGE="\v\tUSAGE: [OPTIONS] [SESSIONFILE]
-\n\t-z, --session\tUse entered SESSIONFILE rather than default
-\t-h, --help\tPrint this usage message and exit
-\n\tWith no command argument, the script uses the current WM session file
-\n\t\t$SESSIONFILE
-\v\tTo start session at login, add the following line to autostart:
-\v\t\tsleep 1; manjaro-polybar-session &"
-TITLE="Manjaro Polybar Manager"
-ICON="--window-icon=/usr/share/icons/hicolor/scalable/apps/manjaro.svg"
-
 case $1 in
-    -h|-H|*help)
-        echo -e "$USAGE" && exit 0
-        ;;
-    -z|*session)
+    -h|-H|--help) echo -e "$USAGE" ; exit 0 ;;
+    -z|--session)
         if [[ $2 ]]; then
             SESSIONFILE=$2
         else
-            echo "Invalid Session.. Exiting" && exit 2
+            echo "Invalid Session.. Exiting" ; exit 2
         fi
 esac
 
+if ! [[ -d $CONFPATH ]] && [[ -d /etc/skel/.config/polybar ]]; then
+    cp -rf /etc/skel/.config/polybar "$HOME/.config/"
+elif ! [[ -d $CONFPATH ]]; then
+    mkdir -p "$CONFPATH" ; cp -f /usr/share/doc/polybar/config "$CONFPATH/config"
+fi
+
 running_Bars() {
-    TEMPFILE=$(mktemp --tmpdir polybars.XXXX)
-    if pgrep -a polybar &>/dev/null; then pgrep -a polybar >> "$TEMPFILE"; fi
+    if [[ $(pidof polybar) ]]; then
+        TEMPFILE=$(mktemp --tmpdir polybars.XXXX)
+        pgrep -a polybar >> "$TEMPFILE"
+    fi
 }
 
+readonly FILES=($(find -L "$CONFPATH" -maxdepth 4 -type f))
 find_Bars() {
-    unset n BARS bar_Names barArray checkMark barPath
-    local n=0
     fill_Arrays() {
         barPath[$1]="$2"
         barArray[$1]="$3"
-        if grep -q "$2\ $3$" $TEMPFILE; then checkMark[$1]="TRUE"; else checkMark[$1]="FALSE"; fi
+        if [[ -e $TEMPFILE ]] && grep -q "$2 $3" "$TEMPFILE"; then
+            checkMark[$1]="TRUE"
+        else
+            checkMark[$1]="FALSE"
+        fi
     }
-    for config in $(find -L "$CONFPATH" -maxdepth 4 -type f); do
-        bar_Names=($(grep '^\[bar/.*\]$' $config | sed 's/]//' | cut -d '/' -f2))
+
+    local n=0
+    for config in "${FILES[@]}"; do
+        bar_Names=($(grep '^\[bar/.*\]$' "$config" | sed 's/]//' | cut -d '/' -f2))
         for bar in "${bar_Names[@]}"; do
-            if [[ "$bar" != "master" ]]; then fill_Arrays $n $config $bar; fi
+            [[ "$bar" != "master" ]] && fill_Arrays "$n" "$config" "$bar"
             n=$((n + 1))
         done
     done
-    for ((i=0; i<=${#barArray[@]}; i++)); do BARS="$BARS ${checkMark[$i]} ${barArray[$i]}"; done
+
+    BARS=""
+    for ((i=0; i<=${#barArray[@]}; i++)); do
+        BARS="$BARS ${checkMark[$i]} ${barArray[$i]}"
+    done
 }
 
-
-# should only be called by the selection dialog
-# creates sessionfile, adding each returned bar and its path to it
-# Determine best way to start session, if polybar isnt installed echo error message
 create_Session() {
-    mkdir -p $CONFPATH/sessions; echo -e "# Polybar $WM Sessionfile
-    \n# DO NO edit this file, it will be overwritten by manjaro-polyzen\n# Instead make a custom sessionfile and use the -z FILE or --session FILE option
-    \n# To load session at startup use the following line\n\n# sleep 1; manjaro-polybar-session &\n" > "$SESSIONFILE"
+    mkdir -p "$CONFPATH/sessions"
+    echo -e "# Polybar $WM Sessionfile
+# DO NO edit this file, it will be overwritten by al-polyzen
+# Instead make a custom sessionfile and use the -z FILE or --session FILE option
+# To load session at startup use the following line\n\n# sleep 1; al-polybar-session &\n" > "$SESSIONFILE"
     for bar in $ANSWER; do
         for config in "${barPath[@]}"; do
-            if grep -q "^\[bar/$bar\]" "$config" && ! grep -q "^$config\ $bar$" "$SESSIONFILE"; then
-                echo "$config $bar" >> "$SESSIONFILE"
+            if grep -q "^\[bar/$bar\]" "$config" && ! grep -q "$config $bar" "$SESSIONFILE"; then
+                echo "$config $bar" >> "$SESSIONFILE" ; break
             fi
         done
     done
-    while [[ $(pidof polybar) ]]; do pkill polybar; sleep 0.2; done
+    [[ $(pidof polybar) ]] && pkill polybar
     while read -r c b; do
-        if [[ "$c $b" =~ ^#.*$ ]] || [[ "$c $b" == "" ]] || ! [[ -f "$c" ]]; then
+        if [[ "$c $b" =~ ^#.*$ ]] || ! ([[ $c ]] && [[ $b ]]) || ! [[ -f "$c" ]]; then
             continue
-        fi
-        if [[ -e "$c" ]]; then
+        else
             polybar --reload --config="$c" "$b" &
         fi
     done < "$SESSIONFILE"
+
+    sleep 0.5
+    if [[ $(pidof polybar) ]]; then
+        if [[ -f $START ]] && ! grep -q "al-polybar-session" "$START"; then
+            if grep -q "polybar" "$START"; then
+                sed -i '/polybar/ c sleep 1; al-polybar-session &' "$START"
+            elif grep -q "tint2" "$START"; then
+                sed -i '/tint2/ a sleep 1; al-polybar-session &' "$START"
+                sed -i '/tint2/d' "$START"
+            elif grep -q "nitrogen" "$START"; then
+                sed -i '/nitrogen/ a sleep 1; al-polybar-session &' "$START"
+            else
+                sed -i '1s/^/sleep 1; al-polybar-session & \n/' "$START"
+            fi
+        fi
+    fi
 }
 
-
-# loop choice until "OK" is clicked
-# If not returned any bars, ask to to go back to bar selection
-# If returned any number of bars, call outer create_session function
 main() {
     while ! [[ $ANSWER ]]; do
         running_Bars
         find_Bars
-        ANSWER=$(zenity $ICON --list --title="$TITLE" --text="<big><b>Select bars to launch</b></big>
-                        \nRunning bars will be checkmarked\nTo disable a running bar:\n\n\tUn-checkmark it and press Ok" \
-                        --checklist --width=350 --height=400 --multiple --separator=" " \
-                        --column="Select" --column="Bar Name" $BARS)
+        MSG="<big><b>Select bars to launch</b></big>\n\nRunning bars are check marked\n\nTo disable a bar:"
+        MSG="$MSG <b>uncheck and click Ok</b>\n\nSession will be saved to: <b>$(basename "$SESSIONFILE")</b>\n"
+        ANSWER=$($CHECKLIST --title="$TITLE" --text="$MSG" --separator=" " --column="Select" --column="Bars" $BARS)
         if [[ $? == 1 ]]; then
-            exit 0
+            ANSWER=NONE
         elif ! [[ $ANSWER ]]; then
-            SURE=$(zenity $ICON --title="$TITLE" --question --width=300 --height=150 \
-                          --ok-label="Go Back to Choice" --cancel-label="Stop Running Bars" \
-                          --text="<big><b>No Bars Selected</b></big>\n\nWhat would you like to do?" &>/dev/null)
-            if [[ $? == 1 ]]; then
-                while [[ $(pidof polybar) ]]; do pkill polybar; sleep 0.2; done
-                echo -n "" > "$SESSIONFILE"; exit 0
+            if [[ $(pidof polybar) ]]; then
+                MSG="<big><b>No Bars Selected</b></big>\n\nWhat would you like to do?"
+                if $QUESTION --title="$TITLE" --ok-label="Go Back" --cancel-label="Stop Bars" --text="$MSG" &>/dev/null; then
+                    ANSWER="" ; continue
+                else
+                    pkill polybar ; echo -n "" > "$SESSIONFILE" ; ANSWER=NONE
+                fi
             else
-                ANSWER=   # Go Back to Choice
+                ANSWER=NONE
             fi
         else
             create_Session
         fi
-        rm -r "$TEMPFILE"
+        [[ -e $TEMPFILE ]] && rm -r "$TEMPFILE"
     done
 }
 
diff --git a/scripts/manjaro-settings-pipemenu b/scripts/manjaro-settings-pipemenu
--- a/scripts/manjaro-settings-pipemenu
+++ b/scripts/manjaro-settings-pipemenu
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 
-
 # A pipemenu base script/template for creating category based pipemenus
 # written by Nathaniel Maia, December 2017 for Manjaro
 
@@ -11,21 +10,15 @@ NAME="settings"
 PNAME="Settings"
 FAIL_MSG="No Apps Installed"
 
-# make sure these two arrays are the same amount of items
-# if not things will go wrong and you will have blank space
-CMD=(manjaro-panel-chooser arandr nitrogen oomox-gui pamac-manager pavucontrol
+CMD=(al-panel-chooser arandr nitrogen oomox-gui pamac-manager pavucontrol
      gnome-system-monitor wpg rofi-theme-selector xfce4-power-manager-settings
-     gnome-disk-utility xfce4-appearance-settings xfce4-settings-manager
-     )
+     gnome-disk-utility xfce4-appearance-settings xfce4-settings-manager lxappearance)
 DESC=("Panel Chooser" "Screen Settings" Wallpaper Oomox "Package Manager"
       "Audio Settings" "System Monitor" wpgtk "Rofi Theme" "Power Manager"
-      "Disk Uitlity" "Gtk Theme" "Settings Manager"
-      )
+      "Disk Uitlity" "Gtk Theme" "Settings Manager" LXappearance)
 
-# source lib file
-if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
-    exit 1
+if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg" ; exit 1
 fi
 
 menu_Body() {
@@ -37,9 +30,10 @@ menu_Body() {
 }
 
 menuStart "$NAME" "$PNAME"
-num=0
 for x in "${CMD[@]}"; do
-    if hash "$x" &>/dev/null; then num=$((num + 1)); fi
+    if hash "$x" &>/dev/null; then
+        num=1 ; break
+    fi
 done
 if [[ $num -gt 0 ]]; then
     menu_Body
diff --git a/scripts/manjaro-terminmanjaro-pipemenu b/scripts/manjaro-terminmanjaro-pipemenu
--- a/scripts/manjaro-terminmanjaro-pipemenu
+++ b/scripts/manjaro-terminmanjaro-pipemenu
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 
-
 # A pipemenu base script/template for creating category based pipemenus
 # written by Nathaniel Maia, December 2017 for Manjaro
 
@@ -11,17 +10,12 @@ NAME="terminals"
 PNAME="Terminals"
 FAIL_MSG="No Apps Installed"
 
-# make sure these two arrays are the same amount of items
-# if not things will go wrong and you will have blank space
 CMD=(terminator tilda tilix urxvt st termite xfce4-terminal xterm)
 DESC=(Terminator Tilda Tilix Rxvt-Unicode "Suckless Terminal" Termite
-      Xfce4-terminal Xterm
-      )
+      Xfce4-terminal Xterm)
 
-# source lib file
-if ! . "/usr/lib/manjaro/common/manjaro-include.cfg" 2> /dev/null; then
-    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/manjaro-include.cfg"
-    exit 1
+if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
+    echo -e "[ERROR]: Failed to source /usr/lib/manjaro/common/al-include.cfg" ; exit 1
 fi
 
 menu_Body() {
@@ -33,14 +27,20 @@ menu_Body() {
 }
 
 menuStart "$NAME" "$PNAME"
-num=0
 for x in "${CMD[@]}"; do
-    if hash "$x" &>/dev/null; then num=$((num + 1)); fi
+    if hash "$x" &>/dev/null; then
+        num=1 ; break
+    fi
 done
 if [[ $num -gt 0 ]]; then
     menu_Body
 else
     menuSeparator "$FAIL_MSG"
+    if hash pamac-manager &>/dev/null; then
+        menuItem "Install with Package Manager" "pamac-manager"
+    elif hash termite pacli &>/dev/null; then
+        menuItem "Install with Package Manager" "termite -e pacli"
+    fi
 fi
 menuEnd
 
diff --git a/scripts/manjaro-tint2-pipemenu b/scripts/manjaro-tint2-pipemenu
--- a/scripts/manjaro-tint2-pipemenu
+++ b/scripts/manjaro-tint2-pipemenu
@@ -1,51 +1,31 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-#    manjaro-tint2-pipemenu - an Openbox pipemenu for tint2 manipulation
-#    Copyright (C) 2015-2016 damo
-#    Borrowed with love by the Manjaro boys.
-#
-#    This program is free software: you can redistribute it and/or modify
-#    it under the terms of the GNU General Public License as published by
-#    the Free Software Foundation, either version 3 of the License, or
-#    (at your option) any later version.
-#
-#    This program is distributed in the hope that it will be useful,
-#    but WITHOUT ANY WARRANTY; without even the implied warranty of
-#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-#    GNU General Public License for more details.
-#
-#    You should have received a copy of the GNU General Public License
-#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# al-tint2-pipemenu - an Openbox pipemenu for tint2 manipulation
+# Copyright (C) 2015-2016 damo
+# Borrowed with love by the Manjaro boys.
 
-
-MANJARO_COMMON_LIBDIR='/usr/lib/manjaro/common'
-TINT2PATH="$HOME/.config/tint2"
-TINT2RC="$TINT2PATH/tint2rc"
-TZEN="manjaro-tint2zen"
-HELP='    manjaro-tint2-pipemenu an Openbox Pipe Menu for tint2 manipulation
-    It should normally be called from an openbox menu.
+readonly TZEN="al-tint2zen"
+readonly TINT2RC="$HOME/.config/tint2/tint2rc"
+readonly HELP='
+al-tint2-pipemenu an Openbox Pipe Menu for tint2 manipulation
+It should normally be called from an openbox menu.
 
 Options:
     -h --help   show this message
 
-    If manjaro-tint2-pipemenu is called with no options (the usual method),
-    it will output an xml openbox pipemenu for handling tint2 sessions,
-    and editing configuration files.
+If al-tint2-pipemenu is called with no options (the usual method),
+it will output an xml openbox pipemenu for handling tint2 sessions,
+and editing configuration files.
 
 For more information, see "man tint2"
-and "Help">"Tint2" in the Manjaro menu.
-'
-for i in "$@"; do
-    case "$i" in
-    -h|--help)
-        echo "$HELP"
-        exit 0
-        ;;
-    esac
-done
+and Help >> Tint2 in the menu.'
 
-if ! . "$MANJARO_COMMON_LIBDIR/manjaro-include.cfg" 2> /dev/null; then
-    echo $"Error: Failed to source manjaro-include.cfg in $MANJARO_COMMON_LIBDIR" >&2
+case "$@" in
+    -h|--help) echo "$HELP" ; exit 0
+esac
+
+if ! . "/usr/lib/manjaro/common/al-include.cfg" 2>/dev/null; then
+    echo $"Error: Failed to source /usr/lib/manjaro/al-include.cfg" >&2
     exit 1
 fi
 
@@ -56,13 +36,13 @@ loadTEditmenu() {
     else
         menuItem "Default tint2rc" "termite -e '$EDITOR $TINT2RC'"
     fi
-    if [[ $(pidof tint2) ]];then
+    if [[ $(pidof tint2) ]]; then
         menuSubmenu "RunningTint2" "Running Tint2s"
         while read -r pid cmd; do
             if [[ ${cmd%% *} = tint2 ]]; then
                 TINT=${cmd##* }
                 TINT2=${TINT#$HOME/.config/}
-                if [[ $TINT = tint2 ]];then
+                if [[ $TINT = tint2 ]]; then
                     TINT="$TINT2RC"
                     TINT2="Default tint2rc"
                 fi
@@ -79,30 +59,30 @@ loadTEditmenu() {
 
 getTint2s() {
     menuSubmenu "EditTint2" "Edit Tint2s"
-        if type manjaro-tint2edit &>/dev/null;then  # manjaro-tint2edit script found
-            menuItem "Tint2 Editor" "manjaro-tint2edit"
+        if type al-tint2edit &>/dev/null; then
+            menuItem "Tint2 Editor" "al-tint2edit"
         fi
         loadTEditmenu
     menuSubmenuEnd
 }
 
 loadChoosermenu() {
-    if type $TZEN &>/dev/null;then  # manjaro-tint2zen script found
-        menuItem "Tint2 Session GUI" "$TZEN"
+    if type $TZEN &>/dev/null; then
+        menuItem "Tint2 Session" "$TZEN"
     fi
 }
 
 loadRestartmenu() {
     if [[ $(pidof tint2) ]];then
-        if type manjaro-tint2restart &>/dev/null;then  # manjaro-tint2restart script found
-            menuItem "Restart Tint2" "manjaro-tint2restart"
+        if type al-tint2restart &>/dev/null; then
+            menuItem "Restart Tint2" "al-tint2restart"
         fi
-        menuItem "Stop all Tint2s" "pkill tint2"
+        menuItem "Stop Tint2s" "pkill tint2"
     fi
 }
 
 menuStart "Tintmenu" "Tint2"
-menuItem "Tint2 GUI" "tint2conf"
+menuItem "Tint2 Settings" "tint2conf"
 loadChoosermenu
 loadRestartmenu
 getTint2s
